### ISSUE TITLE
pgAdmin 6.13 dockerfile error (cannot run)

### ISSUE THREAD

**Issue by donhuvy** [pgadmin-org/pgadmin4#5337]
I checked with pgAdmin docker images version 6.12, no error. This compose file worked success:

```yml
version: "3.9"
services:
  postgres:
    container_name: postgres-14
#    image: postgres:latest
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./create-databases.sh:/docker-entrypoint-initdb.d/create-databases.sh
      - ./db_persist:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tenant_single_db
    hostname: postgres
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:6.12
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=123456a@
    hostname: pgadmin

# pgAdmin: http://localhost:8080/
```
Then check case error:

File `docker-compose.yml`

```yml
version: "3.9"
services:
  postgres:
    container_name: postgres-14
#    image: postgres:latest
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./create-databases.sh:/docker-entrypoint-initdb.d/create-databases.sh
      - ./db_persist:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tenant_single_db
    hostname: postgres
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:6.13
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=123456a@
    hostname: pgadmin

# pgAdmin: http://localhost:8080/
```
Error https://gist.github.com/donhuvy/4a29e01a3da689d490d3a7a4fa9af4f9

![image](https://user-images.githubusercontent.com/1328316/190548400-6d9d591c-26cb-4ad4-b1f5-aa9827e4af8c.png)

**Comment by nikhil-mohite** [comment]
Hi @donhuvy ,

Did you try refreshing the pgAdmin page after the upgrade?

**Comment by donhuvy** [comment]
I try with pgAdmin 4.14 docker, it works! Thank you.

```
version: "3.9"
services:
  postgres:
    container_name: postgres-14
#    image: postgres:latest
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./create-databases.sh:/docker-entrypoint-initdb.d/create-databases.sh
      - ./db_persist:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tenant_single_db
    hostname: postgres
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:6.14
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=123456a@
    hostname: pgadmin

# pgAdmin: http://localhost:8080/
```
