### ISSUE TITLE
Transaction ID not found in session in Query Tool

### ISSUE THREAD

**Issue by johnneal3** [pgadmin-org/pgadmin4#5453]
Hi --

> **Environment**: pgadmin 6.13 running in the official docker image, postgres 13 (also the official docker image) (note: I have seen this issue with earlier versions as well). This problem seems to have shown up in the last several months, first reported to me on August 9 (postgres 9.6 at the time, and the "latest" pgadmin) ... i.e. we were not experiencing it earlier in the year (Postgres 9.6 then, and whatever the "latest" pgadmin docker image was at the time, sorry I don't have specifics on that.)

```yaml
##
   postgres:
      image: postgres:13
      container_name: postgresdb
      environment:
         - POSTGRES_USER=qlik
         - POSTGRES_PASSWORD=${PASSWORD}
         - POSTGRES_DB=qlikdb
         - PGDATA=/var/lib/postgresql/data
      restart: always
      volumes:
         - postgres-data:/var/lib/postgresql
      ports:
         - 5432
      networks:
         - replnet
      command: -c wal_level=logical -c max_replication_slots=3 -c max_wal_senders=3 -c wal_sender_timeout=60s
##
## Start PGADMIN, listening on port 5430. This will run on the replnet network
## and will allow us to browse the postgres database.
##
   pgadmin:
      image: dpage/pgadmin4:latest
      container_name: pgadmin
      depends_on:
         - postgres
      environment:
         - PGADMIN_DEFAULT_EMAIL=pgadmin@qlik.com
         - PGADMIN_DEFAULT_PASSWORD=${PASSWORD}
         - PGADMIN_LISTEN_PORT=5430
         - PGADMIN_CONFIG_ENABLE_PSQL=True
      restart: always
      volumes:
         - pgadmin-data:/var/lib/pgadmin
         - /testdrive/pgadmin.json:/pgadmin4/servers.json
      ports:
         - 5430:5430
      networks:
         - replnet
##
```

I'm running into the above issue when I open a "Query Tool". Immediately upon opening the tool, I get a message "Not Acceptable", and if I hover over the connection icon at the top, it shows the message "Transaction ID not found in the session". 

![Screenshot 2022-10-19 152800](https://user-images.githubusercontent.com/19823062/196797872-fa7292dd-98b3-4ad9-ad49-83bc7a168760.png)

If I request completion help (CTRL-space), I then also see the "Transaction ID not found" in the Messages area:

![Screenshot 2022-10-19 153915](https://user-images.githubusercontent.com/19823062/196799432-ae7f169c-a2ef-4f2a-b97a-a166e7d30d98.png)

> **Note**: if I use the built-in queries from the left pane, they work without issue. The problem seems to be isolated to the query tool.

![Screenshot 2022-10-19 154210](https://user-images.githubusercontent.com/19823062/196799830-ec903aa8-a934-47d5-9345-4ecc1afbea76.png)

![Screenshot 2022-10-19 154309](https://user-images.githubusercontent.com/19823062/196800047-d7a990e4-d827-49b6-8e6e-0ec21ec881be.png)

I've spent many hours trying to find a solution to this ... I've found some hint that there can be challenges with "shared" connections, but as best I could tell that issue was with Apache on Linux and not related to the gunicorn server used in the pgadmin docker image.  I've also seen suggestions to disconnect / reconnect from the database. No luck there. And I've seen suggestions related to connection timeouts. That didn't seem to have an impact either.

Any guidance would be appreciated.
