### ISSUE TITLE
external database configuration error when pgadmin4 in docker

### ISSUE THREAD

**Issue by kharkevich** [pgadmin-org/pgadmin4#5477]
I'll try to run pgadmin4 with external database configuration:

Based on [documentation](https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html) I should provide parameter ```CONFIG_DATABASE_URI``` started with ```PGADMIN_CONFIG_``` prefix to [configure pgadmin4](https://www.pgadmin.org/docs/pgadmin4/development/config_py.html#config-py)

Docker file example
```yaml
version: '3.1'

services:
  postgres:
      image: postgres:14
      container_name: postgres
      ports:
          - "5432:5432"
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: admin

  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      ports:
          - "5050:80"
      depends_on:
          - postgres
      environment:
        PGADMIN_DEFAULT_EMAIL: test@example.com
        PGADMIN_DEFAULT_PASSWORD: admin
        PGADMIN_CONFIG_CONFIG_DATABASE_URI: "postgres:admin@postgres:/postgres"
```

Error during provisioning
```sh
postgres  | 2022-10-29 16:21:44.180 UTC [1] LOG:  database system is ready to accept connections
pgadmin   | Traceback (most recent call last):
pgadmin   |   File "/pgadmin4/run_pgadmin.py", line 4, in <module>
pgadmin   |     from pgAdmin4 import app
pgadmin   |   File "/pgadmin4/pgAdmin4.py", line 38, in <module>
pgadmin   |     import config
pgadmin   |   File "/pgadmin4/config.py", line 820, in <module>
pgadmin   |     from config_distro import *
pgadmin   |   File "/pgadmin4/config_distro.py", line 13
pgadmin   |     CONFIG_DATABASE_URI = postgres:admin@postgres:/postgres
pgadmin   |                                   ^
pgadmin   | SyntaxError: invalid syntax
pgadmin   | Traceback (most recent call last):
pgadmin   |   File "<string>", line 1, in <module>
pgadmin   |   File "/pgadmin4/config.py", line 820, in <module>
pgadmin   |     from config_distro import *
pgadmin   |   File "/pgadmin4/config_distro.py", line 13
pgadmin   |     CONFIG_DATABASE_URI = postgres:admin@postgres:/postgres
pgadmin   |                                   ^
pgadmin   | SyntaxError: invalid syntax
pgadmin   | usage: gunicorn [OPTIONS] [APP_MODULE]
pgadmin   | gunicorn: error: argument -t/--timeout: invalid int value: ''
pgadmin exited with code 2
```

**Comment by yogeshmahajan-1903** [comment]
@kharkevich This feature is not yet released. You can use snapshot build from [here](docker pull dpage/pgadmin4:snapshot) to test this.

**Comment by kettenbach-it** [comment]
Workaround: Put CONFIG_DATABASE_URI in double-double-quotes:

`PGADMIN_CONFIG_CONFIG_DATABASE_URI="'postgres://.....'"`

**Comment by aaro-n** [comment]
# Docker running example
```
version: '3'
services:
  pgAdmin:
    restart: always
    image: dpage/pgadmin4
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: xxx@gmail.com
      PGADMIN_DEFAULT_PASSWORD: xxx
      PGADMIN_CONFIG_CONFIG_DATABASE_URI: "'postgresql://username:password@IP/domain:5432/database?options=-csearch_path=schema'"
```
# Important Notes
1.The version of pgadmin4 needs to be 6.16 or higher
2.Use `postgresql://` at the beginning of the database URL instead of `postgres://`, otherwise an error will be prompted.
3.The `schema` is best created in advance
# References
1.The database URL starts with `postgres://`, it will prompt`sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres`
1.1[sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres](https://stackoverflow.com/questions/62688256/sqlalchemy-exc-nosuchmoduleerror-cant-load-plugin-sqlalchemy-dialectspostgre)
2.[pgadmin-documentation](https://www.pgadmin.org/docs/pgadmin4/development/external_database.html#:~:text=Using%20specific%20schema%20(It%20is%20recommended%20to%20create%20the%20schema%20in%20advance)%3A)
3.[Schemas](https://supabase.com/docs/reference/postgres/schemas#:~:text=Self%2Dhosting-,Schemas,-Schemas%20are%20like)
