### ISSUE TITLE
Stuck on login page

### ISSUE THREAD

**Issue by sipfix** [pgadmin-org/pgadmin4#5558]
I'm running pgadmin in docker and every time I login it just redirects me back to the login page.  Every link on the login page does the same thing.  I am not sure if I am doing anything wrong, I have debug logging turned on in the console and I don't see anything.

```
pgadmin-1  | ::ffff:172.24.0.1 - - [20/Nov/2022:16:36:28 +0000] "GET / HTTP/1.1" 302 217 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.31.584.290 Safari/537.36"
pgadmin-1  | ::ffff:172.24.0.1 - - [20/Nov/2022:16:36:28 +0000] "GET /login?next=%2F HTTP/1.1" 302 205 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.5249.119 Safari/537.36"
pgadmin-1  | ::ffff:172.24.0.1 - - [20/Nov/2022:16:36:28 +0000] "GET /browser/ HTTP/1.1" 302 237 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.5249.119 Safari/537.36"
pgadmin-1  | ::ffff:172.24.0.1 - - [20/Nov/2022:16:36:28 +0000] "GET /login?next=%2Fbrowser%2F HTTP/1.1" 200 1470 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.5249.119 Safari/537.36"

pgadmin-1  | ::ffff:172.24.0.1 - - [20/Nov/2022:16:36:41 +0000] "POST /authenticate/login HTTP/1.1" 302 205 "http://localhost:5050/login?next=%2Fbrowser%2F" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.31.584.290 Safari/537.36"
pgadmin-1  | ::ffff:172.24.0.1 - - [20/Nov/2022:16:36:41 +0000] "GET /browser/ HTTP/1.1" 302 237 "http://localhost:5050/login?next=%2Fbrowser%2F" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.5249.119 Safari/537.36"
pgadmin-1  | ::ffff:172.24.0.1 - - [20/Nov/2022:16:36:41 +0000] "GET /login?next=%2Fbrowser%2F HTTP/1.1" 200 1471 "http://localhost:5050/login?next=%2Fbrowser%2F" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.5249.119 Safari/537.36"
```

**Comment by yogeshmahajan-1903** [comment]
@sipfix 
Can you please share command you run for creating pgAdmin container? If you are using docker compose, can you please share docker file?

**Comment by sipfix** [comment]
Sure, here's what my compose looks like:

```
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "127.0.0.1:5050:80"
    # volumes:
    #   - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@dev.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
      PGADMIN_DISABLE_POSTFIX: true
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
```
