### ISSUE TITLE
HTTP/2

### ISSUE THREAD

**Issue by khteh** [pgadmin-org/pgadmin4#5604]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
I deploy a `Statefulset` to AWS EKS cluster. However, accessing the application through AWS ALB from chrome browser bumps into `503 Service Temporarily Unavailable`. Chrome debug console shows `h2` being used. Is it the issue with `pgadmin-4` not being `HTTP/2` ready? If so, any plan to support it?

**To Reproduce**

3. See the error

**Expected behavior**

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, OSX monterey]: Ubuntu 22.10
 - Version: [e.g. 6.15] latest docker image tag
 - Mode: [e.g Desktop or Server] Kubernetes cluster `Statefulset`
 - Browser (if running in server mode): [e.g. chrome, safari] Chrome
 - Package type: [e.g. RPM, DEB, Python, Container, etc.] Container

**Additional context**

**Comment by yogeshmahajan-1903** [comment]
@khteh 
I am successfully able to launch pgAdmin AWS EKS cluster with clusterIP type service but with http 1.1 protocol.
However I tried H2 protocol with pgadmin hosted behind apache2 webserver & its working fine. PFA SS. Hence H2 protocol should not be issue. 

<img width="1791" alt="Screenshot 2022-12-06 at 5 12 44 PM" src="https://user-images.githubusercontent.com/16016019/205902697-69088f4d-b9ea-43c6-960e-7668f6a7942c.png">

Can you please share Kubernetes deployment yaml file?

**Comment by khteh** [comment]
Can you share your setup?

**Comment by yogeshmahajan-1903** [comment]
@khteh 
Please find the attached files.

Cluster.yaml
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-cluster
  region: ap-northeast-1
nodeGroups:
   - name: ng1
     desiredCapacity: 1
     instanceType: t2.large
     ssh:
        publicKeyName: admin.key
```

deploy-pgadmin.yml
```
apiVersion: v1
kind: Service
metadata:
  name: pgadmineks
  labels:
    app: pgadmineks
spec:
  ports:
    - port: 80
  selector:
    app: pgadmineks
    tier: frontend
  type: ClusterIP
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: pgadmineks
  labels:
    app: pgadmineks
spec:
  selector:
    matchLabels:
      app: pgadmineks
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pgadmineks
        tier: frontend
    spec:
      containers:
      - image: dpage/pgadmin4
        name: pgadmineks
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "yogesh@db.com"
        - name: PGADMIN_PORT
          value: "80"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "password"
        ports:
        - containerPort: 80
          name: pgadminport
```

kustomization.yml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - deploy-pgadmin.yml
```

[Here](url) are some more solutions to resolve 503 error
