### ISSUE TITLE
OAuth Page Does not Appear

### ISSUE THREAD

**Issue by zozidalom** [pgadmin-org/pgadmin4#5654]
Can somebody help me please with this?

My configuration looks like this:
````
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      OAUTH2_NAME: keycloak
      OAUTH2_DISPLAY_NAME: MyAuth
      OAUTH2_CLIENT_ID: pgadmin
      OAUTH2_CLIENT_SECRET: mysecret
      AUTHENTICATION_SOURCES: "[‘oauth2]"
      OAUTH2_AUTO_CREATE_USER: "True"
      OAUTH2_TOKEN_URL: "https://keycloak.myserver.mydomainending/.well-known/openid-configuration/token"
      OAUTH2_AUTHORIZATION_URL: "https://keycloak.myserver.mydomainending/auth/realms/master/.well-known/openid-configuration/auth"
      OAUTH2_USERINFO_ENDPOINT: userinfo
      OAUTH2_API_BASE_URL: "https://keycloak.myserver.mydomainending/auth/realms/master/.well-known/openid-configuration"
      OAUTH2_ICON: fa-github
      OAUTH2_SCOPE: openid email profile
      OAUTH2_ICON: fa-gitlab
      OAUTH2_BUTTON_COLOR: '#E24329'
      PGADMIN_DEFAULT_EMAIL: "firstname.lastname@myserver.mydomainending"
      PGADMIN_DEFAULT_PASSWORD: "somepassword"
    volumes:
       - ./pgadmin:/var/lib/pgadmin
    restart: unless-stopped
````
