### ISSUE TITLE
[6.18] Azure AD (oauth) sign in not working anymore - Missing "jwks_uri" in metadata

### ISSUE THREAD

**Issue by Alexanerinova** [pgadmin-org/pgadmin4#5666]
After updating from 6.17 to 6.18 our Single-Sign-On via Azure AD does not work anymore. Trying to sign in results in a json document containing the error message. 

**To Reproduce**

1. Open pgAdmin
2. Click on 'Login with Azure AD'
3. Wait for the redirection (or sign in via Azure AD, if needed)
4. See the error

**Expected behavior**

The sign-in should succeed and the pgAdmin dashboard should be displayed.

**Error message**

After getting redirected to `https://pgadmin.yourdomain.com/oauth2/authorize?code=0.ATwAbJ....` the following text is displayed:
```json
{"success":0,"errormsg":"Missing \"jwks_uri\" in metadata","info":"","result":null,"data":null}
```

**Screenshots**

![image](https://user-images.githubusercontent.com/113263664/208990464-ccfcd3d8-0a8e-4f46-b11b-c4f01f667f81.png)

**Server:**
 - OS: Ubuntu (amd64)
 - Version: 18.04.6 LTS

**Desktop:**
 - Browser: Microsoft Edge, Google Chrome & Mozilla Firefox

**Additional context**

- pgAdmin is running behind a reverse-proxy (istio ingress)
- pgAdmin is running inside a container (dpage/pgadmin4:6.18)

**Comment by Rowanto** [comment]
Was testing the same thing using docker container, and SSO with google stopped working too. This is probably due to some library update, which makes it requires some JWKS URI. Pinning the docker container to `dpage/pgadmin4:6.17` fixes the issue

**Comment by khushboovashi** [comment]
This could be due to Authlib package update.

**Comment by rapto** [comment]
I can reproduce the error with gitlab login, too

**Comment by yogeshmahajan-1903** [comment]
@Rowanto 
I could reproduce issue with Azure but not with Google. Could you please provide your OAtuh2 confirmation urls to verify the fix?

**Comment by Alexanerinova** [comment]
@akshay-joshi 

1. Is there a pre-release with your fix on docker hub, so I can test it? 
2. Am I assuming right that `OAUTH2_SERVER_METADATA_URL` should optionally point to the OpenID endpoint (`https://yourauthprovider.com/.well-known/openid-configuration`)?

**Comment by yogeshmahajan-1903** [comment]
> @yogeshmahajan-1903 @akshay-joshi
> 
> Thank's for addressing the issue so quickly.
> 
> 1. Is there a pre-release with your fix on docker hub, so I can test it?
This can be tested with daily builds - docker pull dpage/pgadmin4:snapshot

> 2. Am I assuming right that `OAUTH2_SERVER_METADATA_URL` should optionally point to the OpenID endpoint (`https://yourauthprovider.com/.well-known/openid-configuration`)?
Yes. This varies according to OAtuh2 provider. If not provided then it will passed as None.

**Comment by Alexanerinova** [comment]
> > @yogeshmahajan-1903 @akshay-joshi
> > Thank's for addressing the issue so quickly.
> > 
> > 1. Is there a pre-release with your fix on docker hub, so I can test it?
> >    This can be tested with daily builds - docker pull dpage/pgadmin4:snapshot
> 
> > 2. Am I assuming right that `OAUTH2_SERVER_METADATA_URL` should optionally point to the OpenID endpoint (`https://yourauthprovider.com/.well-known/openid-configuration`)?
> >    Yes. This varies according to OAtuh2 provider. If not provided then it will passed as None.

Ok, I just tested it using Azure AD. Test results are:
1. Omitting the new configuration variable `OAUTH2_SERVER_METADATA_URL` results in the same error. 
2. After configuring the `OAUTH2_SERVER_METADATA_URL` to the OpenID endpoint, the sign-in worked correctly.

**Comment by yogeshmahajan-1903** [comment]
> > > @yogeshmahajan-1903 @akshay-joshi
> > > Thank's for addressing the issue so quickly.
> > > 
> > > 1. Is there a pre-release with your fix on docker hub, so I can test it?
> > >    This can be tested with daily builds - docker pull dpage/pgadmin4:snapshot
> > 
> > 
> > > 2. Am I assuming right that `OAUTH2_SERVER_METADATA_URL` should optionally point to the OpenID endpoint (`https://yourauthprovider.com/.well-known/openid-configuration`)?
> > >    Yes. This varies according to OAtuh2 provider. If not provided then it will passed as None.
> 
> Ok, I just tested it using Azure AD. Test results are:
> 
> 1. Omitting the new configuration variable `OAUTH2_SERVER_METADATA_URL` results in the same error.
> 2. After configuring the `OAUTH2_SERVER_METADATA_URL` to the OpenID endpoint, the sign-in worked correctly.
> 
> Thus, the original bug report would be solved in my opinion, although along with a breaking change regarding the configuration, which should probably be mentioned within the release notes (as a known issue in V6.18 as well as a possibly required configuration adjustment in V6.19).
> 
> Whether OAUTH2 works for providers without OpenID or metadata support, I can't test.

`OAUTH2_SERVER_METADATA_URL ` is an optional parameter. I have tested change with Github, where server_meta_data url is not required.

**Comment by Alexanerinova** [comment]
Sounds great. Thank you. :-)

**Comment by Silvenga** [comment]
@Alexanerinova what settings are you using for `OAUTH2_SERVER_METADATA_URL`? It appears tenanted idp doesn't provide a correct `iss` claim when using the tenanted URL e.g. `https://login.microsoftonline.com/<tenant id>/.well-known/openid-configuration`.

**Comment by Alexanerinova** [comment]
> @Alexanerinova what settings are you using for `OAUTH2_SERVER_METADATA_URL`? It appears tenanted idp doesn't provide a correct `iss` claim when using the tenanted URL e.g. `https://login.microsoftonline.com/<tenant id>/.well-known/openid-configuration`.

You should probably use the v2.0 URL instead (should look like `https://login.microsoftonline.com/<tenant id>/v2.0/.well-known/openid-configuration`). 

Our current configuration looks like this and works fine, so far. Please note that this configuration allows missing users to be created automatically within pgAdmin4 and thus access should probably be restricted within the AAD.
```yaml
OAUTH2_AUTO_CREATE_USER = True
OAUTH2_CONFIG = [{
  'OAUTH2_NAME': 'azuread',
  'OAUTH2_DISPLAY_NAME': '<display name>'
  'OAUTH2_CLIENT_ID': '<client id>',
  'OAUTH2_CLIENT_SECRET': '<client secret>'
  'OAUTH2_TOKEN_URL': 'https://login.microsoftonline.com/<tenant id>/oauth2/v2.0/token',
  'OAUTH2_AUTHORIZATION_URL': 'https://login.microsoftonline.com/<tenant id>/oauth2/v2.0/authorize',
  'OAUTH2_API_BASE_URL': 'https://login.microsoftonline.com/<tenant id>/oauth2/v2.0/',
  'OAUTH2_USERINFO_ENDPOINT': 'https://graph.microsoft.com/oidc/userinfo',
  'OAUTH2_SERVER_METADATA_URL': 'https://login.microsoftonline.com/<tenant id>/v2.0/.well-known/openid-configuration',
  'OAUTH2_SCOPE': 'openid profile email offline_access',
  'OAUTH2_ICON': 'building',
  'OAUTH2_BUTTON_COLOR': '#333399',
  'OAUTH2_AUTO_CREATE_USER': True,
}]
```

**Comment by Silvenga** [comment]
Thanks @Alexanerinova - good to know about the `OAUTH2_USERINFO_ENDPOINT=https://graph.microsoft.com/oidc/userinfo`, that seems better then our `https://graph.microsoft.com/v1.0/` hit for the email claim - I know the pgadmin docs say just use the `oid` claim, but we couldn't confirm if that claim is actually sent in the correct format.

**Comment by senkarabacak** [comment]
> With the 6.19 docker container we are still experiencing this with Auth0.

Same for us too, we have also tried all recommendation on config file but the problem has been not solved

**Comment by benedikt-bartscher** [comment]
same here with 6.19 and authentik

**Comment by khushboovashi** [comment]
> same here with 6.19 and authentik

@senkarabacak, @benedikt-bartscher,

Provide your OAuth2 Configuration of pgAdmin, that will help us to understand the issue.

**Comment by benedikt-bartscher** [comment]
> > same here with 6.19 and authentik
> 
> @senkarabacak, @benedikt-bartscher,
> 
> Provide your OAuth2 Configuration of pgAdmin, that will help us to understand the issue.

Hey @khushboovashi thanks for your response.
I configured pgadmin and authentik following the authentik wiki: https://goauthentik.io/integrations/services/pgadmin/
It stopped working with this error msg since 6.18:
```{"success":0,"errormsg":"Missing \"jwks_uri\" in metadata","info":"","result":null,"data":null}```

I tried adding 
```
'OAUTH2_SERVER_METADATA_URL': 'https://authentik.COMPANY.TLD/application/o/pgadmin/.well-known/openid-configuration'
```
to my pgadmin config, but this results in the following error:
```
{"success":0,"errormsg":"Invalid key set format","info":"","result":null,"data":null}
```
i then selected a signing key for the pgadmin authentik provider but again no luck:
```
{"success":0,"errormsg":"unsupported_algorithm: ","info":"","result":null,"data":null}
```

**Comment by benedikt-bartscher** [comment]
I got my issue solved thanks to @BeryJu. A restart of pgadmin is required after selecting a signing key in authentik. This ensures pgadmin useses the latest metadata from the metadata url.

**Comment by senkarabacak** [comment]
> I got my issue solved thanks to @BeryJu. A restart of pgadmin is required after selecting a signing key in authentik. This ensures pgadmin useses the latest metadata from the metadata url.

Thank to you, restarting has helped.

**Comment by rapto** [comment]
Using a self managed instance of gitlab as oauth provider, filling `OAUTH2_SERVER_METADATA_URL` solves the issue.
In case it helps anyone, this is how I solved it:
I created the file `/.well-known/openid-configuration` at the proxy web server and filled it taking https://gitlab.com/.well-known/openid-configuration as an example (not very pretty, since there might be a more elegant way to generate it from live config data).

**Comment by zeqk** [comment]
This issue still happening in 6.19 and 6.20 version, but not in 6.17 version

**Comment by yogeshmahajan-1903** [comment]
@zeqk 
Could you please provide your OAuth2 Configuration of pgAdmin, that will help us to understand the issue.
Have you restarted pgAdmin after updating oauth2 config?

**Comment by nidhikaushal** [comment]
Hi I am facing the same issue, config_distro.py file looks like: 
`{
        # The name of the of the oauth provider, ex: github, google
        'OAUTH2_NAME': 'OKTA',
        # The display name, ex: Google
        'OAUTH2_DISPLAY_NAME': 'OKTA',
        # Oauth client id
        'OAUTH2_CLIENT_ID': '0xxxxx',
        # Oauth secret
        'OAUTH2_CLIENT_SECRET': 'Pxxxxxxxxx',
        # URL to generate a token,
        # Ex: https://github.com/login/oauth/access_token
        'OAUTH2_TOKEN_URL': 'https://athenahealthpoc.okta.com/oauth2/xxxx/v1/token',
        # URL is used for authentication,
        # Ex: https://github.com/login/oauth/authorize
        'OAUTH2_AUTHORIZATION_URL': 'https://athenahealthpoc.okta.com/oauth2/xxxx/v1/authorize?idp=yyyyy',
        # server metadata url might optional for your provider
        'OAUTH2_SERVER_METADATA_URL': 'https://athenahealthpoc.okta.com/.well-known/openid-configuration',
        # Oauth base url, ex: https://api.github.com/
        'OAUTH2_API_BASE_URL': None,
        # Name of the Endpoint, ex: user
        'OAUTH2_USERINFO_ENDPOINT': None,
        # Oauth scope, ex: 'openid email profile'
        # Note that an 'email' claim is required in the resulting profile
        'OAUTH2_SCOPE': 'openid',
        # The claim which is used for the username. If the value is empty the
        # email is used as username, but if a value is provided,
        # the claim has to exist.
        'OAUTH2_USERNAME_CLAIM': None,
        # Font-awesome icon, ex: fa-github
        'OAUTH2_ICON': None,
        # UI button colour, ex: #0000ff
        'OAUTH2_BUTTON_COLOR': '#0000ff',
    }
`

**Comment by zeqk** [comment]
@yogeshmahajan-1903 yes! I am using pgadmin container in kubernetes


(Replace 00000000-0000-0000-0000-000000000000 with a valid tenantId and clientId)

```yml

apiVersion: v1
kind: Secret
metadata:
  name: pgadmin
type: Opaque
stringData:
   OAUTH2_CONFIG: |
          [
            {
                'OAUTH2_NAME': 'azure',
                'OAUTH2_DISPLAY_NAME': 'Azure',
                'OAUTH2_CLIENT_ID': '00000000-0000-0000-0000-000000000000',
                'OAUTH2_CLIENT_SECRET': 'a0a0a0a0a0a',
                'OAUTH2_TOKEN_URL': 'https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000/oauth2/v2.0/token', 
                'OAUTH2_AUTHORIZATION_URL': 'https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000/oauth2/v2.0/authorize',
                'OAUTH2_API_BASE_URL': 'https://graph.microsoft.com/v1.0/',
                'OAUTH2_SERVER_METADATA_URL': 'https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration',
                'OAUTH2_USERINFO_ENDPOINT': 'me',
                'OAUTH2_SCOPE': 'User.Read email openid profile',
                'OAUTH2_BUTTON_COLOR': '#2F2F2F',
                'OAUTH2_ICON': 'fa-brands fa-microsoft',
                'OAUTH2_AUTO_CREATE_USER': True
            }
          ]
```

```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:6.20 #But no problem in dpage/pgadmin4:6.17
          imagePullPolicy: IfNotPresent
          env:
            - name: PGADMIN_CONFIG_AUTHENTICATION_SOURCES
              value: "['oauth2']"
            - name: OAUTH2_AUTO_CREATE_USER
              value: "True"
            - name: PGADMIN_CONFIG_OAUTH2_CONFIG
              valueFrom:
                secretKeyRef:
                  name: pgadmin
                  key: OAUTH2_CONFIG
            - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
              value: "True"
            - name: PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED
              value: "False"
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgadmin
                  key: PGADMIN_DEFAULT_EMAIL
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin
                  key: password
            - name: PGADMIN_PORT
              value: "80"
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 1024Mi
```

**Comment by yogeshmahajan-1903** [comment]
@zeqk 
'OAUTH2_SERVER_METADATA_URL' url should be 'https://login.microsoftonline.com/{tenant}/v2.0' where tenant value deepened on  the application's sign-in audience. Try replacing tenant by your tenant id. You can check more details about this [here](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc).

**Comment by zeqk** [comment]
@yogeshmahajan-1903 thank you very much for your response! It`s works now!

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:6.21
          imagePullPolicy: IfNotPresent
          env:
            - name: PGADMIN_CONFIG_AUTHENTICATION_SOURCES
              value: "['oauth2']"
            - name: OAUTH2_AUTO_CREATE_USER
              value: "True"
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: pgadmin
                  key: CLIENT_ID
            - name: CLIEND_SECRET
              valueFrom:
                secretKeyRef:
                  name: pgadmin
                  key: CLIEND_SECRET
            - name: TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: pgadmin
                  key: TENANT_ID
            - name: PGADMIN_CONFIG_OAUTH2_CONFIG
              value: |
                [
                  {
                      'OAUTH2_NAME': 'azure',
                      'OAUTH2_DISPLAY_NAME': 'Azure',
                      'OAUTH2_CLIENT_ID': '$(CLIENT_ID)',
                      'OAUTH2_CLIENT_SECRET': '$(CLIEND_SECRET)',
                      'OAUTH2_TOKEN_URL': 'https://login.microsoftonline.com/$(TENANT_ID)/oauth2/v2.0/token',
                      'OAUTH2_AUTHORIZATION_URL': 'https://login.microsoftonline.com/$(TENANT_ID)/oauth2/v2.0/authorize',
                      'OAUTH2_API_BASE_URL': 'https://graph.microsoft.com/v1.0/',
                      'OAUTH2_SERVER_METADATA_URL': 'https://login.microsoftonline.com/$(TENANT_ID)/v2.0/.well-known/openid-configuration',
                      'OAUTH2_USERINFO_ENDPOINT': 'me',
                      'OAUTH2_SCOPE': 'User.Read email openid profile',
                      'OAUTH2_BUTTON_COLOR': '#2F2F2F',
                      'OAUTH2_ICON': 'fa-brands fa-microsoft',
                      'OAUTH2_AUTO_CREATE_USER': True
                  }
                ]
            - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
              value: "True"
            - name: PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED
              value: "False"
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgadmin
                  key: PGADMIN_DEFAULT_EMAIL
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin
                  key: password
            - name: PGADMIN_PORT
              value: "80"
          ports:
            - containerPort: 80
```
