### ISSUE TITLE
Backup and restore a PostgreSQL database on PgAdmin 4 using the program's graphical interface

### ISSUE THREAD

**Issue by fedegibut** [pgadmin-org/pgadmin4#5739]
Hello everybody,
I read this guide and noticed some malfunctions:
https://www.pgadmin.org/docs/pgadmin4/6.18/backup_and_restore.html
I read this page:
https://www.pgadmin.org/support/issues/
so I started this thread.

1) **Program version and how I got the software**

Dockerfile 1

`FROM dpage/pgadmin4:6.18`

Dockerfile 2

`FROM kartoza/postgis:15-3.3`

Docker Compose

```
  postgresql-postgis:
    build: ./postgresql-postgis
    image: image-postgresql-postgis-eb:v.1.0
    container_name: container-postgresql-postgis-eb
    restart: always
    networks:
      - eb
    volumes:
      - data-postgresql:/var/lib/postgresql
    environment:
      POSTGRES_USER: "..."
      POSTGRES_PASSWORD: "..."
      POSTGRES_DB: "..."
      ALLOW_IP_RANGE: "0.0.0.0/0"
    depends_on:
      - traefik

  pgadmin:
    build: ./pgadmin
    image: image-pgadmin-eb:v.1.0
    container_name: container-pgadmin-eb
    restart: always
    networks:
      - eb
    labels:
      traefik.http.services.pgadmin.loadbalancer.server.port: 80
      traefik.http.services.pgadmin.loadbalancer.server.scheme: http
      traefik.http.routers.pgadmin.rule: Host(`www.pgadmin.${NOME_A_DOMINIO}`)
      traefik.http.routers.pgadmin.tls.domains[0].main: pgadmin.${NOME_A_DOMINIO}
      traefik.http.routers.pgadmin.tls.domains[0].sans: www.pgadmin.${NOME_A_DOMINIO}
      traefik.http.routers.pgadmin.tls.certresolver: leresolver
    volumes:
      - type: bind
        source: ./volumes/data-pgadmin/servers.json
        target: /pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: ...@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ...
    depends_on:
      - traefik
      - postgresql-postgis
```

servers.json

```
{
  "Servers": {
    "1": {
      "Group": "Server PostgreSQL e PostGIS",
      "Name": "Server 1",
      "Port": 5432,
      "Username": "...",
      "Host": "postgresql-postgis",
      "SSLMode": "prefer",
      "MaintenanceDB": "postgres"
    }
  }
}
```

2) **How am I using the program**
I have installed pgAdmin on a server and I access the service by typing pgadmin.domainname.it

3) **Steps to reproduce the problem**
(see attached photos)

![A](https://user-images.githubusercontent.com/82219403/212544010-7a0755fa-03aa-4713-ad47-85c3257fc3c9.png)

![B](https://user-images.githubusercontent.com/82219403/212544016-8e4a227c-8840-42bf-b3c8-6d2303f2ab32.png)

Note: I actually ran a lot of tests trying to change the backup and restore methods. It is physically impossible to list them all in this discussion. I do not exclude that among all these attempts there is one that works.

4) **OS and browser used**
OS of the server where Docker is installed and where the PgAdmin container runs: Ubuntu 22.04.1 LTS 64bit - cpu arm Ampere of Oracle (updated)
OS of my PC: Windows 10 Pro 64bit cpu intel eighth series (updated)
Browser used: Chrome (latest version)

5) **Error provided by PgAdmin**
(see photos)

![C](https://user-images.githubusercontent.com/82219403/212544095-bfa62df0-2efe-4aea-a6ba-b5c6410bd197.png)

6) **What I have under the hood and what I want to do**
I have an application that allows users to register. I register with the following credentials:
Username: Federico
Password: abc1
Next I backup the database as shown above.
Next I change the password using my application:
Username: Federico
Password: abc2
Finally I restore all the database tables as shown above. Using the browser I should login to the application using the following credentials:
Username: Federico
Password: abc1
Instead I have to use the following:
Username: Federico
Password: abc2
I also get the error shown above warning me that the restore didn't happen.
**I think this is a bug in PgAdmin 4 (6.18 version).**

If you need any other information let me know.
_I tried doing everything on pgadmin.localhost and Linux Desktop 22.04.1 LTS but I get the same errors._

`pg_restore: error: input file appears to be a text format dump. Please use psql.`

Thank you
