### ISSUE TITLE
Servers not populated. servers.json config not used in 6.19

### ISSUE THREAD

**Issue by pratikyoff** [pgadmin-org/pgadmin4#5751]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
servers.json file in /pgadmin4/servers.json is not used and servers are not populated in v6.19. Working as intended with 6.18.
Here is my servers.json file
```
{
    "Servers": {
      "1": {
        "Name": "local-db",
        "Group": "Servers",
        "Host": "dev-postgres",
        "Port": 5432,
        "MaintenanceDB": "postgres",
        "Username": "user",
        "PassFile": "/pgpass",
        "SSLMode": "prefer"
      }
    }
  }
  ```

**To Reproduce**
This is the docker-compose.yml which I am using to run pgadmin4 and postgres
```
version: "3.8"
services:
  db:
    image: postgres
    container_name: dev-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: dev-pgadmin4
    restart: always
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./.config/pgAdmin/servers.json:/pgadmin4/servers.json
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:

```

Click on Servers.
It does not get populated with the existing server configuraiton.

**Desktop (please complete the following information):**
 - OS: macOS 13.0.1
 - Version: 6.19
 - Mode: Server
 - Browser Firefox
 - Package type: Container
