### ISSUE TITLE
'AnonymousUser' object has no attribute 'username' setup.py --load-servers

### ISSUE THREAD

**Issue by tsschubert** [pgadmin-org/pgadmin4#5772]
**Describe the bug**

Initializing pgadmin with a server.json file at `/pgadmin4/servers.json` results in the following error:
`'AnonymousUser' object has no attribute 'username'`

Any invocation of the `/venv/bin/python3 /pgadmin4/setup.py --load-servers "${PGADMIN_SERVER_JSON_FILE}" --user` comand fails with a similar error.

**To Reproduce**

1. Use a docker-compose file like:
```
version: '3.8'
services:
  db:
    container_name: pg
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.19
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
      - LOG_LEVEL=trace
    ports:
      - "5050:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
```
Where servers.json looks something like:
```
{
  "Servers": {
    "1": {
      "Name": "Minimally Defined Server",
      "Group": "Server Group 1",
      "Port": 5432,
      "Username": "postgres",
      "Host": "docker_postgres_db",
      "SSLMode": "prefer",
      "PassFile": ".pgpass",
      "MaintenanceDB": "postgres",
      "Shared": false
    }
  }
}
```

2. docker-compose up
3. View error message in stdout

**Expected behavior**
The setup.py --load-servers should load the servers for the user.
The output of the initialization should show: 
```
----------
Loading servers with:
User: pgadmin@pgadmin.com
SQLite pgAdmin config: /var/lib/pgadmin/pgadmin4.db
----------
Added 1 Server Group(s) and 1 Server(s).
```

**Error message**

The output from initialization shows:
```
----------
Loading servers with:
User: pgadmin@pgadmin.com
SQLite pgAdmin config: /var/lib/pgadmin/pgadmin4.db
----------
'AnonymousUser' object has no attribute 'username'
```

**Additional context**

This is only happening on 6.19+. Correct behavior is seen in both 6.18 and 6.17.
