### ISSUE TITLE
Upgrade broke the docker installation

### ISSUE THREAD

**Issue by valerykustov** [pgadmin-org/pgadmin4#5898]
Hello!

I have a pgadmin4 server running in docker. The docker-compose.yml is the following:
```
version: '3'

services:
  pgadmin:
    image: dpage/pgadmin4:6.18
    environment:
      PGADMIN_DEFAULT_EMAIL: my_email
      PGADMIN_DEFAULT_PASSWORD: my_password
    volumes:
       - ./pgadmin_data:/var/lib/pgadmin
       - ./config_local.py:/pgadmin4/config_local.py
    ports:
      - "some_ip:5050:80"
    restart: unless-stopped
```

I've tried to upgrade the installation with replacing the `image` key in this file with `dpage/pgadmin4:6.20` and running `docker-compose down && docker-compose up -d`. The downloading of the newer image went well. However it didn't start. `docker-compose logs` are attached in 6.20.log. After that I've tried to upgrade to 6.19 at least, but it failed, too. And now I can not revert to 6.18 neither. Both logs for 6.19 and 6.18 are attached with respective names, too. Though it seems to me that all of the logs are about the same problem with a migration.

How do I fix that without reinstalling the pgAdmin4 completely? Any advice is appreciated!

Logs:
[6.20.log](https://github.com/pgadmin-org/pgadmin4/files/10834594/6.20.log)
[6.19.log](https://github.com/pgadmin-org/pgadmin4/files/10834595/6.19.log)
[6.18.log](https://github.com/pgadmin-org/pgadmin4/files/10834596/6.18.log)
