### ISSUE TITLE
Updating ca certificate for pgadmin

### ISSUE THREAD

**Issue by nidhikaushal** [pgadmin-org/pgadmin4#6095]
I have enabled Oauth2 for pgadmin(4.6.20). 

I need to use the ca certificate signed by my company.  

I have created a cacert.pem file under /pgadmin4 as the config.py file mentioned  

`CA_FILE = os.path.join(os.path.dirname(os.path.realpath(__file__)),  "cacert.pem")     `            
                                                             
 Still I am getting the error (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:997)')))","info":"","result":null,"data":null}  

In config_distro.py the location of CA_FILE = /etc/ssl/certs/ca-certificates.crt  I have even updated the contents of this file but still getting the same error.  There are no other config files like config_local.py and config_system.py  What can I do to fix the above error

The way I updated the certificate is by editing  /etc/ssl/certs/ca-certificates.crt and copy pasting  the content from my *.cer file which had data like -----BEGIN CERTIFICATE----- xxxxx -----END CERTIFICATE-----

1. Configure Oauth
2. Add cacert.pem or update /etc/ssl/certs/ca-certificates.crt as per your pgadmin configuration
3. restart pgadmin
4. Login using oauth and see the error 

**Expected behavior**

Login should be allowed

**Error message**

(Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:997)')))","info":"","result":null,"data":null}  

**Desktop (please complete the following information):**
 - OS: linux
 - Version: 6.20
 - Mode: server
 - Browser (if running in server mode): chrome
 - Package type: container

**Comment by yogeshmahajan-1903** [comment]
While starting SSL/TLS enabled container, SSL certificates & key are required to be pass as mentioned [here](https://www.pgadmin.org/docs/pgadmin4/7.1/container_deployment.html#examples).

```
docker pull dpage/pgadmin4
docker run -p 443:443 \
    -v /private/var/lib/pgadmin:/var/lib/pgadmin \
    -v /path/to/certificate.cert:/certs/server.cert \
    -v /path/to/certificate.key:/certs/server.key \
    -v /tmp/servers.json:/pgadmin4/servers.json \
    -e 'PGADMIN_DEFAULT_EMAIL=user@domain.com' \
    -e 'PGADMIN_DEFAULT_PASSWORD=SuperSecret' \
    -e 'PGADMIN_ENABLE_TLS=True' \
    -d dpage/pgadmin4
```

**Comment by dpage** [comment]
@yogeshmahajan-1903, @hasonhai is correct; they are different certificates. The root certificate discussed here (CA_FILE in config.py) is used primarily for network operations by urllib/requests etc, i.e when we do the upgrade check.

My guess is that that path is not being passed down to whatever library is used for OAuth. Please check. Thanks!

**Comment by yogeshmahajan-1903** [comment]
Sure. Let me check the issue.

**Comment by khushboovashi** [comment]
@hasonhai, are you using a self-signed certificate?

**Comment by khushboovashi** [comment]
@hasonhai,

pgAdmin uses the Authlib library for OAuth2 implementation. This error occurs only in the case of a self-signed certificate, Ref: https://github.com/lepture/authlib/issues/239. As a workaround, they proposed to set the ENV variable CURL_CA_BUNDLE=''.

We can make that happen from the pgAdmin app, but currently, as a workaround, you can try and let us know the result.

**Comment by zachradtka** [comment]
Setting `CURL_CA_BUNDLE` to `""` no longer works in authlib [version 2.28.0](https://requests.readthedocs.io/en/latest/community/updates/#release-history) 

The issue is discussed in this [issue 6071](https://github.com/psf/requests/issues/6071)

I had to downgrade pgAdmin to version 6.21 to get OAuth working with a self signed CA.

A suggested solution is in this comment(https://github.com/psf/requests/issues/6071#issuecomment-1059528942)

> they should either expose a configurable endpoint or method to disable verification which is then passed to requests verify argument

**Comment by stephan2012** [comment]
While `CA_FILE` does not work for me, too, setting `REQUESTS_CA_BUNDLE` works.

E.g., `REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt` (assuming you have mounted your CA file here).

**Comment by notsuchus** [comment]
> While `CA_FILE` does not work for me, too, setting `REQUESTS_CA_BUNDLE` works.
> 
> E.g., `REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt` (assuming you have mounted your CA file here).

Please help.
Which environment file did you add this variable to?

**Comment by notsuchus** [comment]
> > 
> 
> @khushboovashi Thanks. The issue was solved by setting that ENV var.

It's a standart `/etc/environment` file or in pgadmin4 path?

I installed pgadmin4 from APT and have analogue issue.

**Comment by stephan2012** [comment]
> Please help. Which environment file did you add this variable to?

The config in the Kubernetes Deployment looks like this:

```yaml
    spec:
      containers:
      - env:
        […]
        - name: REQUESTS_CA_BUNDLE
          value: /etc/ssl/certs/ca-certificates.crt
        […]
        volumeMounts:
        […]
        - mountPath: /etc/ssl/certs
          name: ca-certificates
          readOnly: true
      […]
      volumes:
      […]
      - name: ca-certificates
        secret:
          defaultMode: 256
          secretName: ca-certificates
```

Or, in the [Helm chart](https://artifacthub.io/packages/helm/runix/pgadmin4) values file:

```yaml
env:
  […]
  variables:
    - name: REQUESTS_CA_BUNDLE
      value: /etc/ssl/certs/ca-certificates.crt

[…]

extraSecretMounts:
  - name: ca-certificates
    mountPath: /etc/ssl/certs
    secret: ca-certificates
    readOnly: true
    subPath: ""
```

Of course, you need to create the Kubernetes Secret holding the `ca-certificates.crt` file externally.

**Comment by notsuchus** [comment]
> I have the same issue. Variations I tried:
> 
>     1. Copied complete CA bundle to `/etc/ssl/certs/ca-certificates.pem`
> 
>     2. Copied CA bundle to `/config/cacert.pem` and set `PGADMIN_CONFIG_CA_FILE` environment variable to `'/config/cacert.pem'`
> 
> 
> The error message is:
> 
> ```
> {"success":0,"errormsg":"HTTPSConnectionPool(host='redacted', port=443): Max retries exceeded with url: /realms/master/.well-known/openid-configuration (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')))","info":"","result":null,"data":null}
> ```
> 
> I used the container image `dpage/pgadmin4:7`.

Any luck solving the problem?

I use pgadmin4 installed via pip with gunicorn and nginx.

**Comment by SOLDIERz** [comment]
Is there any progress on this Issue? I'm still facing the Problem that with none of the above solutions to solve this problem in `dpage/pgadmin4:7`

**Comment by yogeshmahajan-1903** [comment]
@SOLDIERz , @notsuchus @vivivanilla ,
Can you please share your docker-compose.yaml? I am not able to reproduce the issue with following docker-compose which supports pgAdmin 4 over SSL.

```
version: "3.3"
  
services:
  pgadmin:
    container_name: dev-pgadmin4
    restart: always
    image: dpage/pgadmin4:7.1
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@edb.com
      PGADMIN_DEFAULT_PASSWORD: adminedb
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
      PGADMIN_ENABLE_TLS: "True"
    volumes:
      - ./config/certificate.cert:/certs/server.cert
      - ./config/certificate.key:/certs/server.key
      - ./config/pgadmin_config_local.py:/pgadmin4/config_local.py:rw
      - ./config/servers.json:/pgadmin4/servers.json
   ```

Ans pgadmin_config_local.py

```
LOGIN_BANNER = "<h4>Authorised Users Only!</h4>"              "Unauthorised use is strictly forbidden."
AUTHENTICATION_SOURCES = ['oauth2', 'internal']
OAUTH2_AUTO_CREATE_USER = True
DEFAULT_SERVER='pgadmin.yourdomain.com'

OAUTH2_CONFIG = [
    {
        'OAUTH2_NAME': "azure",
        # The display name, ex: Google
        'OAUTH2_DISPLAY_NAME': 'MS Azure',
        # Oauth client id
        'OAUTH2_CLIENT_ID': '<client id>',
        # Oauth secret
        'OAUTH2_CLIENT_SECRET': '<client secret>',
        # URL to generate a token,
        # Ex: https://github.com/login/oauth/access_token
        'OAUTH2_TOKEN_URL': 'https://login.microsoftonline.com/<tenant>/oauth2/v2.0/token',
        # URL is used for authentication,
        # Ex: https://github.com/login/oauth/authorize
        'OAUTH2_AUTHORIZATION_URL': 'https://login.microsoftonline.com/<tenant>/oauth2/v2.0/authorize',
        # Oauth base url, ex: https://api.github.com/
        'OAUTH2_API_BASE_URL': 'https://graph.microsoft.com/v1.0/',
        # Name of the Endpoint, ex: user
        'OAUTH2_USERINFO_ENDPOINT': 'me',
        # Oauth scope, ex: 'openid email profile'
        # Note that an 'email' claim is required in the resulting profile
        'OAUTH2_SCOPE': 'User.Read email openid profile',
        # Font-awesome icon, ex: fa-github
        'OAUTH2_ICON': 'fa-github',
        # UI button colour, ex: #0000ff
        'OAUTH2_BUTTON_COLOR': None,
        'OAUTH2_SERVER_METADATA_URL': 'https://login.microsoftonline.com/<tenant>/v2.0/.well-known/openid-configuration'

            }
]

**Comment by yogeshmahajan-1903** [comment]
Can you please share your docker-compose.yaml? I am not able to reproduce the issue with following docker-compose which supports pgAdmin 4 over SSL.

docker-compose - 
```
version: "3.3"
  
services:
  pgadmin:
    container_name: dev-pgadmin4
    restart: always
    image: dpage/pgadmin4:7.1
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@edb.com
      PGADMIN_DEFAULT_PASSWORD: adminedb
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
      PGADMIN_ENABLE_TLS: "True"
    volumes:
      - ./config/certificate.cert:/certs/server.cert
      - ./config/certificate.key:/certs/server.key
      - ./config/pgadmin_config_local.py:/pgadmin4/config_local.py:rw
      - ./config/servers.json:/pgadmin4/servers.json
```

```
DEFAULT_SERVER='pgadmin.yourdomain.com'
LOGIN_BANNER = "<h4>Authorised Users Only!</h4>"              "Unauthorised use is strictly forbidden."
AUTHENTICATION_SOURCES = ['oauth2', 'internal']
OAUTH2_AUTO_CREATE_USER = True
OAUTH2_CONFIG = [
    {
        'OAUTH2_NAME': "azure",
        # The display name, ex: Google
        'OAUTH2_DISPLAY_NAME': 'MS Azure',
        # Oauth client id
        'OAUTH2_CLIENT_ID': '<client id>',
        # Oauth secret
        'OAUTH2_CLIENT_SECRET':'<client secret>',
        # URL to generate a token,
        # Ex: https://github.com/login/oauth/access_token
        'OAUTH2_TOKEN_URL': 'https://login.microsoftonline.com/<tenant>/oauth2/v2.0/token',
        # URL is used for authentication,
        # Ex: https://github.com/login/oauth/authorize
        'OAUTH2_AUTHORIZATION_URL': 'https://login.microsoftonline.com/<tenant>/oauth2/v2.0/authorize',
        # Oauth base url, ex: https://api.github.com/
        'OAUTH2_API_BASE_URL': 'https://graph.microsoft.com/v1.0/',
        # Name of the Endpoint, ex: user
        'OAUTH2_USERINFO_ENDPOINT': 'me',
        # Oauth scope, ex: 'openid email profile'
        # Note that an 'email' claim is required in the resulting profile
        'OAUTH2_SCOPE': 'User.Read email openid profile',
        # Font-awesome icon, ex: fa-github
        'OAUTH2_ICON': 'fa-github',
        # UI button colour, ex: #0000ff
        'OAUTH2_BUTTON_COLOR': None,
        'OAUTH2_SERVER_METADATA_URL': 'https://login.microsoftonline.com/<tenant>/v2.0/.well-known/openid-configuration'

            }
]
```
