### ISSUE TITLE
ERD tool does not work in pgadmin:7 if backend storage is a postgresql database

### ISSUE THREAD

**Issue by Torkolis** [pgadmin-org/pgadmin4#6159]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
This is the docker compose file I am using
```
services:
  pgadmin:
    image: docker.io/dpage/pgadmin4:7
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=p4ssw0rd
      - PGADMIN_ENABLE_TLS=True
      - PGADMIN_CONFIG_CONFIG_DATABASE_URI='postgresql://pgadmin:pgadmin@dbhost.domain.com:5432/pgadmin'
    ports:
      - "443:443"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - /opt/certificates/server-cert.pem:/certs/server.cert
      - /opt/certificates/server-key.pem:/certs/server.key

volumes:
  pgadmin_data:
```
when creating ERD I get this error in the UI:
```
{"success":0,"errormsg":"(psycopg.errors.UndefinedFunction) operator does not exist: integer = character varying\nLINE 3: WHERE server.id = $1::VARCHAR \n                        ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.\n[SQL: SELECT server.id AS server_id, server.user_id AS server_user_id, server.servergroup_id AS server_servergroup_id, server.name AS server_name, server.host AS server_host, server.port AS server_port, server.maintenance_db AS server_maintenance_db, server.username AS server_username, server.password AS server_password, server.save_password AS server_save_password, server.role AS server_role, server.comment AS server_comment, server.discovery_id AS server_discovery_id, server.db_res AS server_db_res, server.passexec_cmd AS server_passexec_cmd, server.passexec_expiration AS server_passexec_expiration, server.bgcolor AS server_bgcolor, server.fgcolor AS server_fgcolor, server.service AS server_service, server.use_ssh_tunnel AS server_use_ssh_tunnel, server.tunnel_host AS server_tunnel_host, server.tunnel_port AS server_tunnel_port, server.tunnel_username AS server_tunnel_username, server.tunnel_authentication AS server_tunnel_authentication, server.tunnel_identity_file AS server_tunnel_identity_file, server.tunnel_password AS server_tunnel_password, server.shared AS server_shared, server.kerberos_conn AS server_kerberos_conn, server.cloud_status AS server_cloud_status, server.connection_params AS server_connection_params, servergroup_1.id AS servergroup_1_id, servergroup_1.user_id AS servergroup_1_user_id, servergroup_1.name AS servergroup_1_name \nFROM server LEFT OUTER JOIN servergroup AS servergroup_1 ON servergroup_1.id = server.servergroup_id \nWHERE server.id = %(id_1)s::VARCHAR \n LIMIT %(param_1)s::INTEGER]\n[parameters: {'id_1': '3', 'param_1': 1}]\n(Background on this error at: https://sqlalche.me/e/20/f405)","info":"","result":null,"data":null}
```
**To Reproduce**

1. start pgadmin:7 with postgres database as backend storage
2. connect to a database
3. create ERD for a database

**Expected behavior**

ERD created correctly

**Error message**

Error (see above) and no ERD

**Additional context**

With pgadmin:6.20 it works (didn't test with 6.21), 7.0 does not work.
