### ISSUE TITLE
Can't use accounts with .local emails

### ISSUE THREAD

**Issue by countessellis** [pgadmin-org/pgadmin4#6222]
Good Morning,

I have an air gapped environment I'm trying to run PgAdmin4 in. I'm currently running 4.7, with the 4.7 docker image. When my users attempt to log in with LDAP, or if I try to create an account for someone, I get the following error:

The domain name <email domain> is a special-use or reserved name that cannot be used with email

In this environment all emails are in a domain ending with .local. Is there any way to make PgAdmin4 allow email addressed with that naming? If not, is there a way to prevent it from populating the email field on successful LDAP login? If there isn't a way, can a way be added?

I'm having troubles tracking down where the error message comes from in the source, so I'm not sure how I could modify it.

Thanks,
~Bethany

**Comment by adityatoshniwal** [comment]
Hi @countessellis,
pgAdmin internally uses https://pypi.org/project/email-validator/ package which do not allow special use domain names listed here - https://www.iana.org/assignments/special-use-domain-names/special-use-domain-names.xhtml.
A workaround suggested is to remove the special domain using the below code:
```
import email_validator
email_validator.SPECIAL_USE_DOMAIN_NAMES.remove("local")
```
You can put this code in custom `config_local or config_system` file. Please read https://www.pgadmin.org/docs/pgadmin4/7.0/config_py.html#the-config-py-file for more details.

Thanks.

**Comment by countessellis** [comment]
Thanks, that worked!

**Comment by adityatoshniwal** [comment]
It would be wise to introduce a new config var `ALLOW_SPECIAL_EMAIL_DOMAINS = []` as an array so that users do not need to add a code snippet and would work directly using env var.
I'm reopening this issue.

**Comment by AlexWinder** [comment]
> Hi @countessellis, pgAdmin internally uses https://pypi.org/project/email-validator/ package which do not allow special use domain names listed here - https://www.iana.org/assignments/special-use-domain-names/special-use-domain-names.xhtml. A workaround suggested is to remove the special domain using the below code:
> 
> ```
> import email_validator
> email_validator.SPECIAL_USE_DOMAIN_NAMES.remove("local")
> ```
> 
> You can put this code in custom `config_local.py or config_system.py` file. Please read https://www.pgadmin.org/docs/pgadmin4/7.0/config_py.html#the-config-py-file for more details.
> 
> Thanks.

This no longer works as of `8.11`, or at least in my Docker environment I am getting a repetitive spam of `'admin@test.local' does not appear to be a valid email address. Please reset the PGADMIN_DEFAULT_EMAIL environment variable and try again.`. 

I'm not sure why this decision has been made because some systems don't sit on a server with a FQDN, and I don't feel particularly comfortable with exposing something easily guessable such as `example.com`, or worst, to make use of a genuine registered FQDN.

How is this solved in `8.11` please so that we can continue to use pgAdmin?

**Comment by yogeshmahajan-1903** [comment]
Working fine.Verified on candidate build.

**Comment by AlexWinder** [comment]
I have got the above working with this:

```
pgadmin:
        image: docker.io/dpage/pgadmin4:8.12
        restart: unless-stopped
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@test.local
            - PGADMIN_DEFAULT_PASSWORD=${DB_PASSWORD}
            - PGADMIN_DISABLE_POSTFIX=True
            - PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS=['local']
        volumes:
            - ./config/pgadmin/servers.json:/pgadmin4/servers.json:rw,z
        depends_on:
            - database
```

This works for Docker, although it's a little confusing because the domain being used isn't `local`, that's the TLD. Rather the domain is `test.local`. 

Given that the actual environment variable is named as `ALLOW_SPECIAL_EMAIL_DOMAINS` this suggests that it would be a list of FQDN, rather than the TLD. This is somewhat confusing from a users POV - at least from my testing whereby I would be expecting to input `test.local` for the domain, rather than `local`.
