### ISSUE TITLE
Using 0 as value for pgadmin container env vars no longer works

### ISSUE THREAD

**Issue by bazylhorsey** [pgadmin-org/pgadmin4#6475]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

      PGADMIN_CONFIG_SERVER_MODE: 0
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 0

In order for these commands to work they need to be set to "False"
There seems to have been a change that caused this to no longer work. 
I would argue 0 should be a functional boolean value when setting the container.

**To Reproduce**

```yaml
version: "3.8"

services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - pgadmin_data:/var/lib/pgadmin:rw
    ports:
      - 15432:15432
    env_file: ".env"
    environment:
      PGADMIN_CONFIG_SERVER_MODE: 0
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 0
      # Default user for desktop mode (SERVER_MODE = False)
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      # Default password for desktop mode (SERVER_MODE = False)
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 15432
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo '${DATABASE_HOST}:5432:*:${DATABASE_USER}:${DATABASE_PASSWORD}' > /tmp/pgpassfile && /entrypoint.sh"

volumes:
  pgadmin_data:
```

**Expected behavior**

setting the environment vars to 0 should equate to Python's falsey val.

**Error message**

```bash
pgadmin  | postfix/postlog: starting the Postfix mail system
pgadmin  | Traceback (most recent call last):
pgadmin  |   File "<string>", line 1, in <module>
pgadmin  |   File "/pgadmin4/config.py", line 881, in <module>
pgadmin  |     from pgadmin.evaluate_config import evaluate_and_patch_config
pgadmin  |   File "/pgadmin4/pgadmin/evaluate_config.py", line 50, in <module>
pgadmin  |     config_distro_settings = get_variables_from_module('config_distro')
pgadmin  |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pgadmin  |   File "/pgadmin4/pgadmin/evaluate_config.py", line 23, in get_variables_from_module
pgadmin  |     variables = {key: value for key, value in module.__dict__.items()
pgadmin  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pgadmin  |   File "/pgadmin4/pgadmin/evaluate_config.py", line 25, in <dictcomp>
pgadmin  |     validate_config_variable(key, value)}
pgadmin  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pgadmin  |   File "/pgadmin4/pgadmin/evaluate_config.py", line 38, in validate_config_variable
pgadmin  |     raise ValueError(exception_msg)
pgadmin  | ValueError: Expected boolean value for SERVER_MODE; got 0
pgadmin  | usage: gunicorn [OPTIONS] [APP_MODULE]
pgadmin  | gunicorn: error: argument -t/--timeout: invalid int value:
```

**Desktop (please complete the following information):**
 - OS: Docker on WSL, also tested on Mac M1
 - Attempted Mode: Server
 - Package type: Container
