### ISSUE TITLE
Flask no longer installed/accessible on container

### ISSUE THREAD

**Issue by bazylhorsey** [pgadmin-org/pgadmin4#6476]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**
running setup.py to initialize database with server configs fails because flask no longer seems to be installed.

**To Reproduce**

1. Set up container
```yaml
version: "3.8"

services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - pgadmin_data:/var/lib/pgadmin:rw
    ports:
      - 15432:15432
    env_file: ".env"
    environment:
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      # Default user for desktop mode (SERVER_MODE = False)
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      # Default password for desktop mode (SERVER_MODE = False)
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 15432
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo '${DATABASE_HOST}:5432:*:${DATABASE_USER}:${DATABASE_PASSWORD}' > /tmp/pgpassfile && /entrypoint.sh"

volumes:
  pgadmin_data:
```

2. run setup.py
```bash
docker exec -it pgadmin python /pgadmin4/setup.py --load-servers servers.json
```

**Expected behavior**

Since setup.py is still a file on pgadmin4, it seems reasonable that required dependencies to run the file are installed to fit the intended behavior.

**Error message**

```bash
Traceback (most recent call last):
  File "/pgadmin4/setup.py", line 24, in <module>
    import config
  File "/pgadmin4/config.py", line 25, in <module>
    from pgadmin.utils import env, IS_WIN, fs_short_path
  File "/pgadmin4/pgadmin/__init__.py", line 24, in <module>
    from flask import Flask, abort, request, current_app, session, url_for
ModuleNotFoundError: No module named 'flask'
make: *** [Makefile:128: load-server-pgadmin] Error 1
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Docker on WSL2, Mac M1]
 - Mode: Server
 - Package type: Container
