### ISSUE TITLE
Issue at os.chmod(config.SESSION_DB_PATH, 0o700) In Azure Container Apps

### ISSUE THREAD

**Issue by mnadeem** [pgadmin-org/pgadmin4#6527]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

PGadmin fails to start in Azure Container apps, when volume is mounted. it fails as `os.chmod(config.SESSION_DB_PATH, 0o700)`

Azure Container apps by default create file system with 777, and does not allow to change and hence the error.

**To Reproduce**

1. Create Container app with **volume mounted**

```

  template:
    containers:
    - env:
      - name: PGADMIN_DEFAULT_EMAIL
        value: abc@abc.com
      - name: PGADMIN_LISTEN_ADDRESS
        value: 0.0.0.0
      - name: PGADMIN_LISTEN_PORT
        value: '5050'
      - name: SECRETENV
        secretRef: anothersecret
      - name: PGADMIN_DEFAULT_PASSWORD
        secretRef: pg-admin-def-pwd
      - name: SCRIPT_NAME
        value: /pgadmin
      image: dpage/pgadmin4:latest
      name: orx-ice-dev-pgadmin-ca
      resources:
        cpu: 0.25
        ephemeralStorage: 1Gi
        memory: 0.5Gi
      volumeMounts:
      - mountPath: /var/lib/pgadmin
        volumeName: pgadmin-data-vol
    initContainers: null
    revisionSuffix: ''
    scale:
      maxReplicas: 1
      minReplicas: 1
      rules: null
    volumes:
    - name: pgadmin-data-vol
      storageName: pgadmin-data-mount
      storageType: AzureFile
  workloadProfileType: null
```

Application fails to startup with following error.

<img width="316" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/476145/19e00644-ac3a-440f-b25c-8c39ab45f563">

**Expected behavior**

**Is there any way to bypass the chmod (Config param ?) so that application can be deployed in ACA ?**

**Error message**

<img width="316" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/476145/19e00644-ac3a-440f-b25c-8c39ab45f563">

**Desktop (please complete the following information):**
 - Azure
 - Version: latest
 - Mode: ACA
 - Browser (if running in server mode): [e.g. chrome, safari]
 - Package type: [e.g. RPM, DEB, Python, Container, etc.] : Container

**Additional context**
