### ISSUE TITLE
Can't set pgpass file

### ISSUE THREAD

**Issue by tamis-laan** [pgadmin-org/pgadmin4#6617]
What ever I try I can't set the pgpass file. I'm using kubernetes and create pgadmin as a deployment:

``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  selector:
    matchLabels:
      app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin4
          image: dpage/pgadmin4
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@join.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: admin
            - name: PGADMIN_PORT
              value: "80"
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgresql-superuser
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-superuser
                  key: password
            - name: POSTGRES_PGPASS
              valueFrom:
                secretKeyRef:
                  name: postgresql-superuser
                  key: pgpass
            - name: PGADMIN_SERVER_JSON_FILE
              value: "/var/lib/pgadmin/servers.json"
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo $POSTGRES_PGPASS> /var/lib/pgadmin/pgpass
              chmod 600 /var/lib/pgadmin/pgpass
              chown pgadmin /var/lib/pgadmin/pgpass
              echo '{
                "Servers": {
                  "1": {
                    "Name": "Postgres server",
                    "Group": "Servers",
                    "Host": "postgresql-rw",
                    "Port": 5432,
                    "MaintenanceDB": "postgres",
                    "Username": "'"$POSTGRES_USERNAME"'",
                    "KerberosAuthentication": false,
                    "ConnectionParameters": {
                        "sslmode": "prefer",
                        "passfile": "/var/lib/pgadmin/pgpass"
                    }
                  }
                }
              }' > /var/lib/pgadmin/servers.json
              /entrypoint.sh
          ports:
            - containerPort: 80
              name: pgadminport
```

is this some sort of bug?
