### ISSUE TITLE
Unable to run in Openshift 4.12. Getting /entrypoint.sh: line 65: /venv/bin/python3: Operation not permitted

### ISSUE THREAD

**Issue by venmaniselvan** [pgadmin-org/pgadmin4#6694]
Hi

Below is the error message, while using pgadmin4:7.5 (https://hub.docker.com/r/dpage/pgadmin4)  in OpenShift 4.12. Can you please help me with this? 

```
/entrypoint.sh: line 65: /venv/bin/python3: Operation not permitted
/entrypoint.sh: line 76: /venv/bin/python3: Operation not permitted
sudo: The "no new privileges" flag is set, which prevents sudo from running as root.
sudo: If sudo is running in a container, you may need to adjust the container configuration to disable the flag.
/entrypoint.sh: line 88: /venv/bin/python3: Operation not permitted
/entrypoint.sh: exec: line 96: /venv/bin/gunicorn: Operation not permitted
```

**To Reproduce**
deploymentconfig_pgadmin.yaml
```

kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  annotations:
  name: pgadmin
  namespace: pgadmin
  labels:
    app: pgadmin
    app.kubernetes.io/component: pgadmin
    app.kubernetes.io/instance: pgadmin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pgadmin
    app.kubernetes.io/version: 0.1.0
    chart: pgadmin-0.1.0
    release: pgadmin
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
      annotations:
        rollme: LvC0U
    spec:
      volumes:
        - name: pgadmin-app-config
          configMap:
            name: pgadmin-app-config
            defaultMode: 436
      containers:
        - resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          name: pgadmin
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@admin.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: admin
            - name: PGADMIN_LISTEN_PORT
              value: '5050'
            - name: PGADMIN_LISTEN_ADDRESS
              value: 0.0.0.0
          securityContext: {}
          ports:
            - name: http
              containerPort: 5050
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: pgadmin-app-config
              mountPath: /pgadmin4/config_local.py
              subPath: config_local.py
            - name: pgadmin-app-config
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
          terminationMessagePolicy: File
          image: 'dpage/pgadmin4:7.5'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler

```
configmap.yaml

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: pgadmin-app-config
  namespace: pgadmin
  labels:
    app.kubernetes.io/managed-by: Helm
data:
  config_local.py: |-
    import os
    _BASEDIR = '/var/lib/pgadmin/data'
    LOG_FILE = os.path.join(_BASEDIR, 'logfile')
    SQLITE_PATH = os.path.join(_BASEDIR, 'sqlite.db')
    STORAGE_DIR = os.path.join(_BASEDIR, 'storage')
    SESSION_DB_PATH = os.path.join(_BASEDIR, 'sessions')
  servers.json: |
    {
      "Servers": {
        "0": {
          "Name": "PostgreSQL",
          "Group": "Servers",
          "Port": 5432,
          "Username": "postgres",
          "Host": "sample.text.com",
          "SSLMode": "prefer",
          "MaintenanceDB": "postgres"
        }
      }
    }

```

Thank you.

**Comment by abinabraham-git** [comment]
Hi @venmaniselvan 

I got the same issue as yours. 

Please follow the below steps to fix the same.

Here the pod tries to use uid 5050 to run the container. By default, open shift security doesn't allow it to run in this range.
Either,

1. we can apply security context constraints to run as _anyuid_ for the namespace.
`
oc adm policy add-scc-to-group anyuid system:serviceaccounts:<namespace>
`
1. Follow the below procedure to enable uid for the current deployment

- Create custom security context constraints 

`
 kind: SecurityContextConstraints
 apiVersion: security.openshift.io/v1
 metadata:
   name: scc-pga
 allowPrivilegedContainer: false
 runAsUser:
   type: MustRunAsRange
   uidRangeMin: 5000
   uidRangeMax: 6000
 seLinuxContext:
   type: RunAsAny
 fsGroup:
   type: MustRunAs
   ranges:
   - min: 5000
     max: 6000
 supplementalGroups:
   type: MustRunAs
   ranges:
   - min: 5000
     max: 6000
`

- Apply security context constraints to the namespace

oc create -f scc.yaml -n <namespace>

- Create a new service account for the deployment, use the following command

oc create sa sa-pga -n <namespace>

- Setup a role and role binding to use SCC and service account. Please use the following resource yaml.

` 
 kind: Role
 apiVersion: rbac.authorization.k8s.io/v1
 metadata:
   name: role-pga
 rules:
   - apiGroups: ["security.openshift.io"]
     resources: ["securitycontextconstraints"]
     resourceNames: ["scc-pga"]
     verbs: ["use"]
 ---
 kind: RoleBinding
 apiVersion: rbac.authorization.k8s.io/v1
 metadata:
   name: role-binding-pga
 subjects:
   - kind: ServiceAccount
     name: sa-pga
 roleRef:
   kind: Role
   name: role-pga
   apiGroup: rbac.authorization.k8s.io
`

- Add the parameter 'serviceAccountName: sa-pga' to the 'deployment.yaml'

`
kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  annotations:
  name: pgadmin
  namespace: pgadmin
  labels:
    app: pgadmin
    app.kubernetes.io/component: pgadmin
    app.kubernetes.io/instance: pgadmin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pgadmin
    app.kubernetes.io/version: 0.1.0
    chart: pgadmin-0.1.0
    release: pgadmin
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
      annotations:
        rollme: LvC0U
    spec:
      serviceAccountName: sa-pga
      volumes:
        - name: pgadmin-app-config
          configMap:
            name: pgadmin-app-config
            defaultMode: 436
      containers:
        - resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          name: pgadmin
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@admin.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: admin
            - name: PGADMIN_LISTEN_PORT
              value: '5050'
            - name: PGADMIN_LISTEN_ADDRESS
              value: 0.0.0.0
          ports:
            - name: http
              containerPort: 5050
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: pgadmin-app-config
              mountPath: /pgadmin4/config_local.py
              subPath: config_local.py
            - name: pgadmin-app-config
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
          terminationMessagePolicy: File
          image: 'dpage/pgadmin4:7.5'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
`

- Apply the yaml to create a pgadmin instance

`oc apply -f deployment.yaml -n <namespace>`

Hope this helps to fix your issue.
Thanks

**Comment by yogeshmahajan-1903** [comment]
As per above solution, pgAdmin is working fine. Unfortunately pgAdmin will not be able to fix this. Hence closing the issue.

**Comment by abeltre1** [comment]
> As per above solution, pgAdmin is working fine. Unfortunately pgAdmin will not be able to fix this. Hence closing the issue.

 @yogeshmahajan-1903: why does PGAdmin require a python virtual environment ? Can you simply install all the packages in the container and then start PGAdmin?

**Comment by KorenP1** [comment]
> > As per above solution, pgAdmin is working fine. Unfortunately pgAdmin will not be able to fix this. Hence closing the issue.
> 
> [@yogeshmahajan-1903](https://github.com/yogeshmahajan-1903): why does PGAdmin require a python virtual environment ? Can you simply install all the packages in the container and then start PGAdmin? I am thinking mainly from an OCP perspective. I think everyone else is doing just fine away from OCP.

Me personally on regular k8s but using restricted PSS which requires securityContext of dropping all capabilities.
Currently succeed running it with most restricted securityContext/Random UID but dropping all capabilities doesnt let me running the application without `/venv/bin/python3: Operation not permitted` logs

Currently searching for a solution, if ill find one ill share, if ill find something we can do in the Dockerfile ill send a PR to official pgAdmin

**Comment by KorenP1** [comment]
Hi Everyone
I have found a solution and i wrote a documentation for it. Sorry for the bad frontend, Im not a frontend developer :)
To solve the `Operation not permitted` error you need to  .spec.template.spec.containers[0].securityContext.capabilities.add=["NET_BIND_SERVICE"]

Adding a link for the documentation, for further details feel free to ask me any questions. thanks.
https://korenp1.github.io

**Comment by abeltre1** [comment]
> Hi Everyone I have found a solution and i wrote a documentation for it. Sorry for the bad frontend, Im not a frontend developer :) To solve the `Operation not permitted` error you need to assign the next field in your pod .spec.containers[0].securityContext.capabilities.add=["NET_BIND_SERVICE"] This capability is allowed in both OpenShift restricted-v2 SCC and restricted PSS
> 
> Adding a link for the documentation, for further details feel free to ask me any questions. thanks. https://korenp1.github.io
> 
> [@abeltre1](https://github.com/abeltre1) [@yogeshmahajan-1903](https://github.com/yogeshmahajan-1903) [@abinabraham-git](https://github.com/abinabraham-git) [@venmaniselvan](https://github.com/venmaniselvan)

I will test the details and report back. I have alternatively deployed Adminer. It does the job.

**Comment by ap0phi5** [comment]
I'm seeing this too - unfortunately our local corporate policy does not permit us to add the NET_BIND_SERVICE capability.

I've not quite figured out why it is wanting privileged ports still when you have set the following environment variable:
```
          - name: PGADMIN_LISTEN_PORT
            value: "5050"
```

**Comment by ap0phi5** [comment]
@KorenP1 Thanks for replying - Our restriction is a corporate one that is enforced by OPA/Gatekeeper, rather than something from GKE. We need to run GKE workloads with the following SecurityContext:

```
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 5050
            runAsUser: 5050
            seccompProfile:
              type: RuntimeDefault
```
