### ISSUE TITLE
Cannot connect to Kubernetes Deployment via NodePort

### ISSUE THREAD

**Issue by lkuendig** [pgadmin-org/pgadmin4#6779]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

When I connect via JDBC connection string and Postrgres-driver or from an IntelliJ database-plugin it works. But adding the server from pgAdmin it doesn't. Error message:
Unable to connect to server: connection timeout expired

**To Reproduce**

https://stackoverflow.com/q/71335551/3417684

**Expected behavior**

Login works

**Error message**

Unable to connect to server: connection timeout expired

**Additional context**

- pgAdmin 4 - version 7.6
- postgres.conf: listen_addresses = '*'

**Comment by adityatoshniwal** [comment]
Hi @lkuendig,
This doesn't look like a pgAdmin issue. The issue here your minikube cluster is not accessible from the pgAdmin docker container. May be related to this - https://stackoverflow.com/questions/61686660/how-to-access-the-minikube-from-a-docker-container?

**Comment by lkuendig** [comment]
it's in the same cluster (k8s - not minikube) and the application (from different) host outside of the cluster can access postgres db. also I can access pgAdmin UI. therefore everything seems open from outside the cluster. just the connection between pgAdmin and postgres doesn't work

**Comment by adityatoshniwal** [comment]
Hi @lkuendig ,

Can you please share your k8 config yaml file?

**Comment by lkuendig** [comment]
- postgress deployment:
```
apiVersion: v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: infrastructure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app/srv-default: "true"
        app: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: xxx
            - name: POSTGRES_USER
              value: xxx
            - name: POSTGRES_DB
              value: xxx
          image: postgres:latest
          name: postgres
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-claim0
      restartPolicy: Always
      volumes:
        - name: postgres-claim0
          persistentVolumeClaim:
            claimName: postgres-claim0
status: {}
```
- postgres service:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: infrastructure
spec:
  type: NodePort
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
      nodePort: 32543
  selector:
    app: postgres
status:
  loadBalancer: {}
```

- pgAdmin deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pg-admin
  name: pg-admin
  namespace: infrastructure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-admin
  strategy: {}
  template:
    metadata:
      labels:
        app/srv-default: "true"
        app: pg-admin
    spec:
      containers:
        - env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: xxx@gmail.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: xxx
          image: dpage/pgadmin4
          name: pg-admin
          ports:
            - containerPort: 80
              hostPort: 5050
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
```
- pgAdmin service:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pg-admin
  name: pg-admin
  namespace: infrastructure
spec:
  type: NodePort
  ports:
    - name: "5050"
      port: 5050
      targetPort: 80
      nodePort: 32585
  selector:
    app: pg-admin
status:
  loadBalancer: {}
```

access pgAdmin-UI: http://192.168.1.180:32585 (ok)
access postgres via application: jdbc:postgresql://192.168.1.180:32543/xxx (ok)
access postgres via pgAdmin: 1) 192.168.1.180 - 2) 32543 - 3) xxx - 4) xxx - 5) xxx (NOK)

**Comment by yogeshmahajan-1903** [comment]
@lkuendig 

I am not able to reproduce the issue with above yaml configuration.(Of course I had to add 'PersistentVolumeClaim' for postgres). I have tested on minikune setup.
<img width="1792" alt="Screenshot 2023-09-26 at 4 47 44 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/7c266d1c-b05b-4cc1-a4ad-ed4446913319">

Can you please postgres pod logs once?

Here is my yaml config - 
```

apiVersion: v1
# define a resource for volume chain
kind: PersistentVolumeClaim
metadata:
  # Name the volume chain
  name: postgres-claim0
spec:
  accessModes:
    # Allow ReadWrite to multiple pods
    - ReadWriteMany
  # PVC requesting resources
  resources:
    requests:
      # the PVC storage
      storage: 8Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app/srv-default: "true"
        app: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: xxx
            - name: POSTGRES_USER
              value: xxx
            - name: POSTGRES_DB
              value: xxx
          image: postgres:latest
          name: postgres
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-claim0
      restartPolicy: Always
      volumes:
        - name: postgres-claim0
          persistentVolumeClaim:
            claimName: postgres-claim0
status: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  type: NodePort
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
      nodePort: 32543
  selector:
    app: postgres
status:
  loadBalancer: {}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pg-admin
  name: pg-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-admin
  strategy: {}
  template:
    metadata:
      labels:
        app/srv-default: "true"
        app: pg-admin
    spec:
      containers:
        - env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: abc@gmail.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: xxxx
          image: dpage/pgadmin4
          name: pg-admin
          ports:
            - containerPort: 80
              hostPort: 5050
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pg-admin
  name: pg-admin
spec:
  type: NodePort
  ports:
    - name: "5050"
      port: 5050
      targetPort: 80
      nodePort: 32585
  selector:
    app: pg-admin
status:
  loadBalancer: {}
```
