### ISSUE TITLE
PgAdmin4 container deployment and PasswordExecCommand

### ISSUE THREAD

**Issue by lmeunier-talend** [pgadmin-org/pgadmin4#6792]
Hi,

I'm deploying PgAdmin4 into a kubernetes cluster using the latest dpage/pgadmin4
I have setup a `servers.json` that is read at startup but the `PasswordExecCommand` is ignored and not available in the UI

I have found somewhere in your documentation that this option is only available in `desktop mode` but it doesn't seem possible to set this with the container deployment.

Did I miss something ?

I would like to read the password from a env variable that I set from a kubernetes secret.

**Comment by anilsahoo20** [comment]
Hi @lmeunier-talend,
Yes, this is disabled for server mode. Reason being, a user can set any arbitrary command which will be executed on the server.
We can make it configurable.

**Comment by anilsahoo20** [comment]
@yogeshmahajan-1903 after enabling ENABLE_SERVER_PASS_EXEC_CMD to true in SERVER mode, server.json does not have the `PasswordExecCommand` key.

**Comment by anilsahoo20** [comment]
Tested and verified on snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-01-23/
Package: arm64, pip wheel
Environment: macOs ventura 13.5.1

**Comment by lmeunier-talend** [comment]
Hi has the fix have been released yet ?
I have tried with docker image `pgadmin4:2024-02-08-1` but it was not working

**Comment by anilsahoo20** [comment]
Hi @lmeunier-talend 
By default the PasswordExecCommand control is disabled in Server mode, if you want to enable that control then you have to make ENABLE_SERVER_PASS_EXEC_CMD to True in config file.

This flag will enable the control.

**Comment by lmeunier-talend** [comment]
It still not working for me, here is my conf, there is probably something wrong

```
 - name: psql
    image: dpage/pgadmin4:2024-02-08-1
    imagePullPolicy: Always
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
    volumeMounts:
      - name: servers
        mountPath: /pgadmin4/servers.json
        subPath: servers.json
    env:
      - name: ENABLE_SERVER_PASS_EXEC_CMD
        value: "True"
```

````
data:
  servers.json: |
    {
      "Servers": {
          "1": {
              "Name": "svc1",
              "Group": "Servers",
              "Host": "localhost",
              "Username": "svc-name",
              "PasswordExecCommand": "echo $SVC_PASSWORD",
              "Port": 5432,
              "MaintenanceDB": "postgres",
              "SSLMode": "prefer"
          },
          "2": {
              "Name": "svc2",
              "Group": "Servers",
              "Host": "localhost",
              "Username": "svc-name",
              "PasswordExecCommand": "echo $SVC2_PASSWORD",
              "Port": 5432,
              "MaintenanceDB": "postgres",
              "SSLMode": "prefer"
          }
        }
    }
```
