### ISSUE TITLE
Unable to use pgAdmin4 since 8.2

### ISSUE THREAD

**Issue by DenuxPlays** [pgadmin-org/pgadmin4#7211]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Since PgAdmin 8.2 it is completly unsuable.
I cannot login becasue /login redirects to /login.

**To Reproduce**

1. Set up pgAdmin using docker 
2. try to login
3. See the error

**Expected behavior**

Able to login

**Error message**

See images

**Screenshots**

![image](https://github.com/pgadmin-org/pgadmin4/assets/83671398/7a63156c-2b36-481b-9cb9-aad1a29106d3)

![image](https://github.com/pgadmin-org/pgadmin4/assets/83671398/1eefbb16-e71a-40a8-b10e-da7243287c7b)

**Desktop (please complete the following information):**
 - OS: Fedora 39
 - Version: 8.2 - 8.3
 - Mode: Server
 - Browser Firerfox and Edge
 - Package type: Docker

**Additional context**

Already cleared my docker volume aka complete fresh installation still the same...

PgAdmin runs behind a reverse proxy (caddy) with the simplies setting: (reverse_proxy 127.0.0.1:8080)
Also the firefox error happens sometimes and the other times it just keep loading without making requests to the server.

## Docker compose setup:
```yml
    pgadmin:
        image: dpage/pgadmin4:8.3
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
            PGADMIN_DISABLE_POSTFIX: false
        ports:
            - "127.0.0.1:8080:80"
        volumes:
          - ./system/pga_data:/var/lib/pgadmin
        links:
            - db
        depends_on:
            db:
                condition: service_healthy
````
