### ISSUE TITLE
readOnlyRootFilesystem to true in Kubernetes

### ISSUE THREAD

**Issue by albundy83** [pgadmin-org/pgadmin4#7330]
**Describe the solution you'd like**
Hello,

it will be nice that files that are updated by `entrypoint.sh` file be written to a dedicated **empty** folder.
At least file `/pgadmin4/config_distro.py`.

For moment, we can't use an `emptyDir` or `persistentVolumeClaim` as there are many files in `/pgadmin4` folder.

I will be a nice step to achieve a more secure pgadmin4 Deployment by being capable to set `readOnlyRootFilesystem` to true.

**Describe alternatives you've considered**
Generate my self the `/pgadmin4/config_distro.py` as ConfigMap or Secret and mount it but we should be able to disable generation.

Specify a custom path for `/pgadmin4/config_distro.py` with ENV var.

**Additional context**

**Comment by oldboys92** [comment]
also looking for a solution to this 👍

**Comment by balazsjdp** [comment]
Hey, is there any solution for this?

**Comment by yogeshmahajan-1903** [comment]
@albundy83 , @oldboys92 , @balazsjdp 
Does below configuration solved your issue?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:8.13
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "admin@example.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "admin"
          ports:
            - containerPort: 80
          securityContext:
            readOnlyRootFilesystem: true  # Make the root filesystem read-only
          volumeMounts:
            - name: pgadmin-data
              mountPath: /var/lib/pgadmin
              readOnly: false
            - name: pgadmin-tmp
              mountPath: /tmp  # Mount tmp volume
              readOnly: false
            - name: pgadmin-config-volume
              mountPath: /pgadmin4/config_distro.py
              subPath: config_distro.py
      volumes:
        - name: pgadmin-data
          emptyDir: {}
        - name: pgadmin-tmp
          emptyDir: {}  # Temporary directory that Kubernetes will manage
        - name: pgadmin-config-volume
          configMap:
            name: pgadmin-config-distro

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config-distro
  namespace: default  # You can change this to the desired namespace
data:
  config_distro.py: |
    CA_FILE = '/etc/ssl/certs/ca-certificates.crt'
    LOG_FILE = '/dev/null'
    HELP_PATH = '../../docs'

---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
```

**Comment by albundy83** [comment]
Hello,
sure we could always manage config_distro.py this way.

I can also override the entrypoint.sh that write in this file [here](https://github.com/pgadmin-org/pgadmin4/blob/master/pkg/docker/entrypoint.sh#L43) and manage my self the config_distro.py file.

But it will be so nice to just add a paramter with default value to `/pgadmin4/config_distro.py` and that you could override if you want (for example in /pgadmin4/tmp/config_distro.py) :)

**Comment by pravesh-sharma** [comment]
Working fine.

**Comment by albundy83** [comment]
Hello,

will you release an image soon ?

**Comment by yogeshmahajan-1903** [comment]
@albundy83 
Yes. We have release 8.14 planned for tomorrow.

**Comment by oldboys92** [comment]
@yogeshmahajan-1903 good to know, I'm going to try this out in the next days and provide feedback.

**Comment by albundy83** [comment]
Hello,
just try to export and use the new environment variable `PGADMIN_CUSTOM_CONFIG_DISTRO_FILE`.

I have set it to `PGADMIN_CUSTOM_CONFIG_DISTRO_FILE=/var/lib/pgadmin/config_distro.py` and started my container in Kubernetes but it does not work as the file need to be present due to `wc -m "${CONFIG_DISTRO_FILE_PATH` found in line [here](https://github.com/pgadmin-org/pgadmin4/blob/master/pkg/docker/entrypoint.sh#L45).

If you really need to not override the file each time we start pgadmin container (but maybe it's not a good idea anymore), we could convert the line to this:
```bash
if [ ! -e "${CONFIG_DISTRO_FILE_PATH}" ] || [ "$(wc -m "${CONFIG_DISTRO_FILE_PATH}" 2>/dev/null | awk '{ print $1 }')" = "0" ]; then
```

**Comment by albundy83** [comment]
Hello, @khushboovashi here the PR https://github.com/pgadmin-org/pgadmin4/pull/8258

**Comment by yogeshmahajan-1903** [comment]
> Hello, just try to export and use the new environment variable `PGADMIN_CUSTOM_CONFIG_DISTRO_FILE`.
> 
> I have set it to `PGADMIN_CUSTOM_CONFIG_DISTRO_FILE=/var/lib/pgadmin/config_distro.py` and started my container in Kubernetes but it does not work as the file need to be present due to `wc -m "${CONFIG_DISTRO_FILE_PATH` found in line [here](https://github.com/pgadmin-org/pgadmin4/blob/master/pkg/docker/entrypoint.sh#L45).
> 
> If you really need to not override the file each time we start pgadmin container (but maybe it's not a good idea anymore), we could convert the line to this:
> 
> ```shell
> if [ ! -e "${CONFIG_DISTRO_FILE_PATH}" ] || [ "$(wc -m "${CONFIG_DISTRO_FILE_PATH}" 2>/dev/null | awk '{ print $1 }')" = "0" ]; then
> ```

This will not work if readOnlyRootFilesystem marked as true. But we can add it to enable custom location for config_distro without overriding.

**Comment by albundy83** [comment]
Yes it will work.
readOnlyRootFilesystem does not mean you are not allowed to add a volume that will allow write.
Here a working kubernetes example:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin4
  labels:
    app: pgadmin4
    app.kubernetes.io/component: pgadmin4
    app.kubernetes.io/instance: pgadmin4
    app.kubernetes.io/managed-by: Kustomize
    app.kubernetes.io/name: pgadmin4
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pgadmin4
  template:
    metadata:
      name: pgadmin4
      labels:
        app: pgadmin4
        app.kubernetes.io/component: pgadmin4
        app.kubernetes.io/instance: pgadmin4
        app.kubernetes.io/managed-by: Kustomize
        app.kubernetes.io/name: pgadmin4
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 5050
        runAsGroup: 5050
        fsGroup: 5050
      dnsConfig:
        options:
          - name: ndots
            value: '1'
      containers:
        - name: pgadmin4
          image: docker.io/dpage/pgadmin4:8.14-custom # I modify the entrypoint.sh to add my modification
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5050
              protocol: TCP
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgadmin4
                  key: pgadmin_default_email
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin4
                  key: pgadmin_default_password
            - name: PGADMIN_CUSTOM_CONFIG_DISTRO_FILE
              value: /var/lib/pgadmin/config_distro.py
            - name: PGADMIN_DISABLE_POSTFIX
              value: 'True'
            - name: PGADMIN_LISTEN_PORT
              value: '5050'
          resources:
            limits:
              cpu: '1'
              ephemeral-storage: 2Gi
              memory: 512Mi
            requests:
              cpu: 100m
              ephemeral-storage: '0'
              memory: 64Mi
          volumeMounts:
            - name: pgadmin-lib
              mountPath: /var/lib/pgadmin
            - name: tmp
              mountPath: /tmp
            - name: pgadmin-log
              mountPath: /var/log/pgadmin
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
      volumes:
        - name: pgadmin-lib
          persistentVolumeClaim:
            claimName: pgadmin4
        - name: tmp
          emptyDir: {}
        - name: pgadmin-log
          emptyDir: {}
```
As you can see I use the env var `PGADMIN_CUSTOM_CONFIG_DISTRO_FILE`
```yaml
            - name: PGADMIN_CUSTOM_CONFIG_DISTRO_FILE
              value: /var/lib/pgadmin/config_distro.py
```
But also, I add a volume that will be persistent and writable:
```yaml
          volumeMounts:
            - name: pgadmin-lib
              mountPath: /var/lib/pgadmin
```
But as I say, due to the fact that when updated `config_distro.py` does not exist you need to modify the line to:
```bash
if [ ! -e "${CONFIG_DISTRO_FILE_PATH}" ] || [ "$(wc -m "${CONFIG_DISTRO_FILE_PATH}" 2>/dev/null | awk '{ print $1 }')" = "0" ]; then
```

What do you think ? :)

**Comment by albundy83** [comment]
By the way, /tmp as writable filesystem is mandatory too, if not you will have this error:
```yaml
- name: tmp
          emptyDir: {}
```
If not we have the following error:
```python
[2024-12-16 06:30:04 +0000] [1] [ERROR] Unhandled exception in main loop
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 202, in run
    self.manage_workers()
  File "/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 571, in manage_workers
    self.spawn_workers()
  File "/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 642, in spawn_workers
    self.spawn_worker()
  File "/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker = self.worker_class(self.worker_age, self.pid, self.LISTENERS,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 72, in __init__
    super().__init__(*args, **kwargs)
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 64, in __init__
    self.tmp = WorkerTmp(cfg)
               ^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/gunicorn/workers/workertmp.py", line 24, in __init__
    fd, name = tempfile.mkstemp(prefix="wgunicorn-", dir=fdir)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/tempfile.py", line 350, in mkstemp
    prefix, suffix, dir, output_type = _sanitize_params(prefix, suffix, dir)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/tempfile.py", line 126, in _sanitize_params
    dir = gettempdir()
          ^^^^^^^^^^^^
  File "/usr/lib/python3.12/tempfile.py", line 315, in gettempdir
    return _os.fsdecode(_gettempdir())
                        ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/tempfile.py", line 308, in _gettempdir
    tempdir = _get_default_tempdir()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/tempfile.py", line 223, in _get_default_tempdir
    raise FileNotFoundError(_errno.ENOENT,
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/pgadmin4']
```

**Comment by yogeshmahajan-1903** [comment]
> Yes it will work. readOnlyRootFilesystem does not mean you are not allowed to add a volume that will allow write. Here a working kubernetes example:
> 
> ```yaml
> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   name: pgadmin4
>   labels:
>     app: pgadmin4
>     app.kubernetes.io/component: pgadmin4
>     app.kubernetes.io/instance: pgadmin4
>     app.kubernetes.io/managed-by: Kustomize
>     app.kubernetes.io/name: pgadmin4
> spec:
>   replicas: 1
>   strategy:
>     type: Recreate
>   selector:
>     matchLabels:
>       app: pgadmin4
>   template:
>     metadata:
>       name: pgadmin4
>       labels:
>         app: pgadmin4
>         app.kubernetes.io/component: pgadmin4
>         app.kubernetes.io/instance: pgadmin4
>         app.kubernetes.io/managed-by: Kustomize
>         app.kubernetes.io/name: pgadmin4
>     spec:
>       automountServiceAccountToken: false
>       securityContext:
>         runAsUser: 5050
>         runAsGroup: 5050
>         fsGroup: 5050
>       dnsConfig:
>         options:
>           - name: ndots
>             value: '1'
>       containers:
>         - name: pgadmin4
>           image: docker.io/dpage/pgadmin4:8.14-custom # I modify the entrypoint.sh to add my modification
>           imagePullPolicy: Always
>           ports:
>             - name: http
>               containerPort: 5050
>               protocol: TCP
>           env:
>             - name: PGADMIN_DEFAULT_EMAIL
>               valueFrom:
>                 secretKeyRef:
>                   name: pgadmin4
>                   key: pgadmin_default_email
>             - name: PGADMIN_DEFAULT_PASSWORD
>               valueFrom:
>                 secretKeyRef:
>                   name: pgadmin4
>                   key: pgadmin_default_password
>             - name: PGADMIN_CUSTOM_CONFIG_DISTRO_FILE
>               value: /var/lib/pgadmin/config_distro.py
>             - name: PGADMIN_DISABLE_POSTFIX
>               value: 'True'
>             - name: PGADMIN_LISTEN_PORT
>               value: '5050'
>           resources:
>             limits:
>               cpu: '1'
>               ephemeral-storage: 2Gi
>               memory: 512Mi
>             requests:
>               cpu: 100m
>               ephemeral-storage: '0'
>               memory: 64Mi
>           volumeMounts:
>             - name: pgadmin-lib
>               mountPath: /var/lib/pgadmin
>             - name: tmp
>               mountPath: /tmp
>           securityContext:
>             allowPrivilegeEscalation: false
>             readOnlyRootFilesystem: true
>       volumes:
>         - name: pgadmin-lib
>           persistentVolumeClaim:
>             claimName: pgadmin4
>         - name: tmp
>           emptyDir: {}
> ```
> 
> As you can see I use the env var `PGADMIN_CUSTOM_CONFIG_DISTRO_FILE`
> 
> ```yaml
>             - name: PGADMIN_CUSTOM_CONFIG_DISTRO_FILE
>               value: /var/lib/pgadmin/config_distro.py
> ```
> 
> But also, I add a volume that will be persistent and writable:
> 
> ```yaml
>           volumeMounts:
>             - name: pgadmin-lib
>               mountPath: /var/lib/pgadmin
> ```
> 
> But as I say, due to the fact that when updated `config_distro.py` does not exist you need to modify the line to:
> 
> ```shell
> if [ ! -e "${CONFIG_DISTRO_FILE_PATH}" ] || [ "$(wc -m "${CONFIG_DISTRO_FILE_PATH}" 2>/dev/null | awk '{ print $1 }')" = "0" ]; then
> ```
> 
> What do you think ? :)

Yes When file mapped externally it will work.

**Comment by yogeshmahajan-1903** [comment]
> By the way, /tmp as writable filesystem is mandatory too, if not you will have this error:
> 
> ```yaml
>         - name: tmp
>           emptyDir: {}
> ```
> 
> If not we have the following error:
> 
> ```python
> [2024-12-16 06:30:04 +0000] [1] [ERROR] Unhandled exception in main loop
> Traceback (most recent call last):
>   File "/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 202, in run
>     self.manage_workers()
>   File "/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 571, in manage_workers
>     self.spawn_workers()
>   File "/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 642, in spawn_workers
>     self.spawn_worker()
>   File "/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
>     worker = self.worker_class(self.worker_age, self.pid, self.LISTENERS,
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/venv/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 72, in __init__
>     super().__init__(*args, **kwargs)
>   File "/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 64, in __init__
>     self.tmp = WorkerTmp(cfg)
>                ^^^^^^^^^^^^^^
>   File "/venv/lib/python3.12/site-packages/gunicorn/workers/workertmp.py", line 24, in __init__
>     fd, name = tempfile.mkstemp(prefix="wgunicorn-", dir=fdir)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/tempfile.py", line 350, in mkstemp
>     prefix, suffix, dir, output_type = _sanitize_params(prefix, suffix, dir)
>                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/tempfile.py", line 126, in _sanitize_params
>     dir = gettempdir()
>           ^^^^^^^^^^^^
>   File "/usr/lib/python3.12/tempfile.py", line 315, in gettempdir
>     return _os.fsdecode(_gettempdir())
>                         ^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/tempfile.py", line 308, in _gettempdir
>     tempdir = _get_default_tempdir()
>               ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/tempfile.py", line 223, in _get_default_tempdir
>     raise FileNotFoundError(_errno.ENOENT,
> FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/pgadmin4']
> ```

Yes. because some libs looks for writable tmp directory.

**Comment by albundy83** [comment]
> > Yes it will work. readOnlyRootFilesystem does not mean you are not allowed to add a volume that will allow write. Here a working kubernetes example:
> > ```yaml
> > apiVersion: apps/v1
> > kind: Deployment
> > metadata:
> >   name: pgadmin4
> >   labels:
> >     app: pgadmin4
> >     app.kubernetes.io/component: pgadmin4
> >     app.kubernetes.io/instance: pgadmin4
> >     app.kubernetes.io/managed-by: Kustomize
> >     app.kubernetes.io/name: pgadmin4
> > spec:
> >   replicas: 1
> >   strategy:
> >     type: Recreate
> >   selector:
> >     matchLabels:
> >       app: pgadmin4
> >   template:
> >     metadata:
> >       name: pgadmin4
> >       labels:
> >         app: pgadmin4
> >         app.kubernetes.io/component: pgadmin4
> >         app.kubernetes.io/instance: pgadmin4
> >         app.kubernetes.io/managed-by: Kustomize
> >         app.kubernetes.io/name: pgadmin4
> >     spec:
> >       automountServiceAccountToken: false
> >       securityContext:
> >         runAsUser: 5050
> >         runAsGroup: 5050
> >         fsGroup: 5050
> >       dnsConfig:
> >         options:
> >           - name: ndots
> >             value: '1'
> >       containers:
> >         - name: pgadmin4
> >           image: docker.io/dpage/pgadmin4:8.14-custom # I modify the entrypoint.sh to add my modification
> >           imagePullPolicy: Always
> >           ports:
> >             - name: http
> >               containerPort: 5050
> >               protocol: TCP
> >           env:
> >             - name: PGADMIN_DEFAULT_EMAIL
> >               valueFrom:
> >                 secretKeyRef:
> >                   name: pgadmin4
> >                   key: pgadmin_default_email
> >             - name: PGADMIN_DEFAULT_PASSWORD
> >               valueFrom:
> >                 secretKeyRef:
> >                   name: pgadmin4
> >                   key: pgadmin_default_password
> >             - name: PGADMIN_CUSTOM_CONFIG_DISTRO_FILE
> >               value: /var/lib/pgadmin/config_distro.py
> >             - name: PGADMIN_DISABLE_POSTFIX
> >               value: 'True'
> >             - name: PGADMIN_LISTEN_PORT
> >               value: '5050'
> >           resources:
> >             limits:
> >               cpu: '1'
> >               ephemeral-storage: 2Gi
> >               memory: 512Mi
> >             requests:
> >               cpu: 100m
> >               ephemeral-storage: '0'
> >               memory: 64Mi
> >           volumeMounts:
> >             - name: pgadmin-lib
> >               mountPath: /var/lib/pgadmin
> >             - name: tmp
> >               mountPath: /tmp
> >           securityContext:
> >             allowPrivilegeEscalation: false
> >             readOnlyRootFilesystem: true
> >       volumes:
> >         - name: pgadmin-lib
> >           persistentVolumeClaim:
> >             claimName: pgadmin4
> >         - name: tmp
> >           emptyDir: {}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > As you can see I use the env var `PGADMIN_CUSTOM_CONFIG_DISTRO_FILE`
> > ```yaml
> >             - name: PGADMIN_CUSTOM_CONFIG_DISTRO_FILE
> >               value: /var/lib/pgadmin/config_distro.py
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But also, I add a volume that will be persistent and writable:
> > ```yaml
> >           volumeMounts:
> >             - name: pgadmin-lib
> >               mountPath: /var/lib/pgadmin
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But as I say, due to the fact that when updated `config_distro.py` does not exist you need to modify the line to:
> > ```shell
> > if [ ! -e "${CONFIG_DISTRO_FILE_PATH}" ] || [ "$(wc -m "${CONFIG_DISTRO_FILE_PATH}" 2>/dev/null | awk '{ print $1 }')" = "0" ]; then
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > What do you think ? :)
> 
> Yes When file mapped externally it will work.

It's not a file mapped externally, it's just the fact that you specify a filesystem writable and with the help of your new env variable `PGADMIN_CUSTOM_CONFIG_DISTRO_FILE`, we can now have a real full support for read-only filesystem.

Thanks again :)

**Comment by albundy83** [comment]
It finally works perfectly with the release 9.0.0 :-)
Here my adapted way to deploy it:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin4
  labels:
    app: pgadmin4
    app.kubernetes.io/component: pgadmin4
    app.kubernetes.io/instance: pgadmin4
    app.kubernetes.io/managed-by: Kustomize
    app.kubernetes.io/name: pgadmin4
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pgadmin4
  template:
    metadata:
      name: pgadmin4
      labels:
        app: pgadmin4
        app.kubernetes.io/component: pgadmin4
        app.kubernetes.io/instance: pgadmin4
        app.kubernetes.io/managed-by: Kustomize
        app.kubernetes.io/name: pgadmin4
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 5050
        runAsGroup: 5050
        fsGroup: 5050
      dnsConfig:
        options:
          - name: ndots
            value: '1'
      containers:
        - name: pgadmin4
          image: docker.io/dpage/pgadmin4:9.0.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5050
              protocol: TCP
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgadmin4
                  key: pgadmin_default_email
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin4
                  key: pgadmin_default_password
            - name: PGADMIN_DISABLE_POSTFIX
              value: 'True'
            - name: PGADMIN_LISTEN_PORT
              value: '5050'
            - name: PGADMIN_CUSTOM_CONFIG_DISTRO_FILE
              value: /var/lib/pgadmin/config_distro.py
          livenessProbe:
            httpGet:
              path: /misc/ping
              port: http
              scheme: HTTP
            failureThreshold: 1
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /misc/ping
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /misc/ping
              port: http
            failureThreshold: 30
            periodSeconds: 10
          resources:
            limits:
              cpu: '1'
              ephemeral-storage: 2Gi
              memory: 512Mi
            requests:
              cpu: 100m
              ephemeral-storage: '0'
              memory: 64Mi
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: pgadmin-lib
              mountPath: /var/lib/pgadmin
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
      volumes:
        - name: tmp
          emptyDir: {}
        - name: pgadmin-lib
          persistentVolumeClaim:
            claimName: pgadmin4
```

Thanks a lot !!
