### ISSUE TITLE
Refused to execute script because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

### ISSUE THREAD

**Issue by jmelosegui** [pgadmin-org/pgadmin4#7412]
**Describe the bug**
After deploying pgadmin4 to kubernetes. when I try to access the site, the spinning icon appears, but the page never finish loading.
When inspecting the console I find the following error:
```
Refused to execute script from 'http://my-url.com/login?next=%2Fbrowser%2F' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

**To Reproduce**

1. Deploy pgadming to kubernetes using the following file:
 ```yaml
 apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "my-email@example.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "P@ssw0rd!"
---

apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP # Expose the service outside the cluster

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin-ingress
spec:
  rules:
  - host: my-url.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pgadmin-service
            port:
              number: 8080  # Use the port exposed by your pgadmin-service

 ```
2. Navigate to the URL defined in the ingress
3. The page never loads. Open the console and see the error mentioned above.

**Expected behavior**

the page should load to allow the user to provide the credentials and login to the site.

**Error message**

```
Refused to execute script from 'http://my-url.com/login?next=%2Fbrowser%2F' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```
