### ISSUE TITLE
8.6 in docker : ModuleNotFoundError: No module named 'flask_gravatar'

### ISSUE THREAD

**Issue by flechaig** [pgadmin-org/pgadmin4#7445]
**A clear and concise description of what the bug is.**

Container based on docker image version 8.6 (docker.io/dpage/pgadmin4:latest) fails to start with an error related to Gravatar: ModuleNotFoundError: No module named 'flask_gravatar'

**Steps to reproduce the behavior:**

Upgrade docker image from previous docker.io/dpage/pgadmin4:latest
Recreate the container

**Expected behavior**

Well, should start as before

**Error message**

[2024-05-03 09:10:30 +0200] [87] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/venv/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/pgadmin4/run_pgadmin.py", line 4, in <module>
    from pgAdmin4 import app
  File "/pgadmin4/pgAdmin4.py", line 104, in <module>
    app = create_app()
          ^^^^^^^^^^^^
  File "/pgadmin4/pgadmin/__init__.py", line 735, in create_app
    from .submodules import get_submodules
  File "/pgadmin4/pgadmin/submodules.py", line 3, in <module>
    from .browser import blueprint as BrowserModule
  File "/pgadmin4/pgadmin/browser/__init__.py", line 30, in <module>
    from flask_gravatar import Gravatar
ModuleNotFoundError: No module named 'flask_gravatar'

**Comment by adityatoshniwal** [comment]
Hi @flechaig,
Can you please share the docker run command? This should not happen as we've removed the code shown in the error stack trace.
Thanks.

**Comment by flechaig** [comment]
Hi @adityatoshniwal , thank you for your quick answer.
I do not use docker run but docker compose with this docker-compose.yaml file:
```
  pgadmin:
    container_name: pgadmin0
    environment:
      PGADMIN_LISTEN_ADDRESS: "edited"
      PGADMIN_DEFAULT_EMAIL: edited
      PGADMIN_DEFAULT_PASSWORD: edited
      PGADMIN_ENABLE_TLS: true
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
      TZ: Europe/Paris
      TERM: xterm-256color
    hostname: pgadmin0.docker
    image: dpage/pgadmin4:latest
#    image: dpage/pgadmin4:8.5
    init: true
    mac_address: 02:00:00:00:02:40
    networks:
      bridge1:
        ipv4_address: 172.18.0.40
        ipv6_address: edited
    restart: unless-stopped
    volumes:
      - type: volume
        source: pgadmin0_settings
        target: /pgadmin4
```

What is weird is that even with 8.4 or 8.5 docker image versions, I still see 8.3 as the version pgadmin4 GUI.
