### ISSUE TITLE
server is not listed in the admin UI by default docker-compose through environment variables

### ISSUE THREAD

**Issue by nagkumar** [pgadmin-org/pgadmin4#7462]
```
services:
    postgres:
        container_name: postgres
        image: postgres:15.2-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - "15432:5432"
        restart: unless-stopped

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        restart: always
        environment:
            PGHOST: postgres
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_USER: postgres
            PGADMIN_DEFAULT_PASSWORD: postgres
            PGADMIN_DEFAULT_DB: postgres

        ports:
            - "5050:80"
```

PGAdmin UI does not list the postgress server.. though PGHOST value is given in pgadmin config.. it is better pgadmin support auto configure container db automatically

<img width="689" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/332234/f36e1092-0438-47fe-acbd-7ea569f944e2">
