### ISSUE TITLE
PgAdmin in docker behind nginx reverse proxy

### ISSUE THREAD

**Issue by E-lit** [pgadmin-org/pgadmin4#7723]
I'd like to access PgAdmin on server behind nginx reverse proxy

docker-compose.yml file:

```
services:

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: "********"
      POSTGRES_USER: "************"
      POSTGRES_PASSWORD: "***********"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    expose:
      - 5432
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ************ -d ************"]
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "**********"
      PGADMIN_DEFAULT_PASSWORD: "************"
      PGADMIN_CONFIG_SERVER_MODE: "True"
      PGADMIN_LISTEN_PORT: 8080
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "8080:8080"
    expose:
      - 8080
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
  
   gateway:
    image: nginx:${NGINX_VERSION:-latest}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./gateway_logs:/var/log/nginx
      - ./config/gateway.conf:/etc/nginx/conf.d/default.conf
      - ./ssl-cert:/etc/ssl-cert
    restart: always
    healthcheck:
      test: ["CMD-SHELL","curl -f --insecure https://localhost/ || exit 1"]

```

Nginx config:

```
limit_req_zone $binary_remote_addr zone=api_req_limit:5m rate=15r/s;
limit_conn_zone $binary_remote_addr zone=api_conn_limit:5m;


upstream web-client-api {
    server web-client:80 max_fails=5 fail_timeout=10s;
}

server {
  listen 80;
  server_name www.domain.com;
  client_body_buffer_size 50M;
  client_header_buffer_size 2k;
  large_client_header_buffers 4 8k;
  client_max_body_size 1510M;
  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl;
  http2  on;
  server_name www.domain.com;

  ssl_certificate /etc/ssl-cert/fullchain.pem;
  ssl_certificate_key /etc/ssl-cert/privkey.pem;

  root /usr/share/nginx/html;
  index index.html;
  keepalive_timeout 60;
  keepalive_requests 100;
  send_timeout 10;

  client_body_buffer_size 50M;
  client_header_buffer_size 2k;
  large_client_header_buffers 4 8k;
  client_max_body_size 1510M;

  gzip on;
  gzip_min_length 100;
  gzip_comp_level 4;
  gzip_proxied any;
  gzip_vary on;
  gzip_types application/atom+xml;
  gzip_types application/javascript;
  gzip_types application/json;
  gzip_types application/rss+xml;
  gzip_types application/vnd.ms-fontobject;
  gzip_types application/x-font-ttf;
  gzip_types application/x-web-app-manifest+json;
  gzip_types application/xhtml+xml;
  gzip_types application/xml;
  gzip_types font/opentype;
  gzip_types image/svg+xml;
  gzip_types image/x-icon;
  gzip_types text/css;
  gzip_types text/plain;
  gzip_types text/x-component;
  gzip_disable "msie6";

  server_tokens off; 

  location /pgadmin4/ {
        proxy_set_header X-Script-Name /pgadmin4;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header Host $host;
        proxy_pass http://pgadmint:8080/;
        proxy_redirect off;
    }


  location / {
    proxy_pass http://web-client-api/;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}

```

But if I open URL https://www.domain.com/pgadmin4/  i get -

```
Welcome to nginx!

If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

For online documentation and support please refer to [nginx.org](http://nginx.org/).
Commercial support is available at [nginx.com](http://nginx.com/).

Thank you for using nginx.
```

while direct access http://www.domain.com:8080/ works well

will be very grateful for your help

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: Ubuntu 22.04
 - Mode:  Server
 - Browser (if running in server mode): Firefox
 - Package type: Container
 - Nginx: 1.26-alpine
