### ISSUE TITLE
SERVER_MODE=False doesn't work in Docker container

### ISSUE THREAD

**Issue by MurzNN** [pgadmin-org/pgadmin4#7746]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

I'm setting up pgAdmin4 locally in a Docker container, that will be available only from localhost. 
So, I don't need any login and password authorization.

For this case, pgAdmin provides the `SERVER_MODE=False` mode - https://www.pgadmin.org/faq/#2

But setting this environment variable doesn't help, pgAdmin still requires to enter email and password.

**To Reproduce**

1. Set the `SERVER_MODE=False` environment variable in the Docker container `dpage/pgadmin4`.
2. Start the container. 
3. See that it asks to enter an email and password. 
4. Even if I set them via another env variables, it starts well but asks for the email and password on the web interface.

**Expected behavior**

With the disabled SERVER_MODE, it should allow access to the database without password.

If I make or understood something wrong, please tell me how to configure the local setup of pgAdmin container to not ask entering email and password on each login.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 24.04
 - Mode: Docker image with Docker Compose.
 - Browser: Firefox
 - Package type: Container

**Additional context**
The compose file:
```yaml
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
    - PGADMIN_DEFAULT_EMAIL=foo@example.com
    - PGADMIN_DEFAULT_PASSWORD=db
    - SERVER_MODE=False
```
