### ISSUE TITLE
Persistent use of docker image

### ISSUE THREAD

**Issue by prhbrt** [pgadmin-org/pgadmin4#7808]
I'm trying to get the docker container persistent over down/up-cycles by mounting `/var` and `/pgadmin4` as volumes, but it fails. That is, everything works, except for persistence.

I also tried copying those folders manually to the volumes from a build/up where the volumes weren't mounted.

```
services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=hello@example.com
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/pgadmin_password
      - PGADMIN_SERVER_JSON_FILE=/run/secrets/pgadmin_servers
    volumes:
      - pgadmin4-var:/var
      - pgadmin4-wd:/pgadmin4
    secrets:
      - pgadmin_password
      - pgadmin_servers

secrets:
  pgadmin_password:
    file: secrets/pgadmin_password.txt
  pgadmin_servers:
    file: secrets/pgadmin_servers.json
volumes:
  pgadmin4-var:
  pgadmin4-wd:
```

E.g. I need to login again and also provide the database password, even though I clicked save before.

![image](https://github.com/user-attachments/assets/1a8f8e6b-9c43-420c-834a-dba52d2c95cc)

How can I run this in docker persistently? And why does the configuration with volumes fail?

**Comment by yogeshmahajan-1903** [comment]
Hi,

You need to map 'var/lib/pgadmin/' directory which stores session , db file, log file etc. Kindly refer [this](https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html#mapped-files-and-directories).

A typical docker compose with persistent volume looks like below - 
```
version: "3.8"
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: xxxxxxxx
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      
volumes:
  pgadmin-data:
    name: 'pgadmin-data'
```
