### ISSUE TITLE
[Docker] Email validation does not use custom configuration

### ISSUE THREAD

**Issue by jbod** [pgadmin-org/pgadmin4#7897]
**Describe the bug**

When using pgAdmin4 through the Docker image, the email set in the PGADMIN_DEFAULT_EMAIL variable is validated during the execution of the entrypoint.sh file. However, this does not care about any Python configuration file provided, leading to validation errors whilst setup should allow it.

**To Reproduce**

1. Create a config_system.py file with the following content, to allow .local email addresses:
`import email_validator
email_validator.SPECIAL_USE_DOMAIN_NAMES.remove("local")`
2. Launch the Docker image with the following command:
`docker run -ti --rm -e PGADMIN_DEFAULT_EMAIL=admin@mytest.local -e PGADMIN_DEFAULT_PASSWORD=admin -e PGADMIN_CONFIG_CHECK_EMAIL_DELIVERABILITY=False -v $(pwd)/config_system.py:/etc/pgadmin/config_system.py dpage/pgadmin4`

**Expected behavior**

The Docker image launches, pgAdmin4 is started and I can use the admin@mytest.local email address to authenticate.

**Error message**

The Docker image exits with the following message:
`'admin@mytest.local' does not appear to be a valid email address. Please reset the PGADMIN_DEFAULT_EMAIL environment variable and try again.`

**Environment**
 - Debian 12.6 on WSL2
 - Docker Desktop 4.33.1
 - pgAdmin4 8.11.0

**Additional context**

- Attempting to validate the email address manually using the email_validator Python library works, as long as the content of the config_system.py file is executed before all.
- The error raised within the entrypoint.sh file is the following:
`email_validator.exceptions_types.EmailSyntaxError: The part after the @-sign is a special-use or reserved name that cannot be used with email.`

**Comment by yogeshmahajan-1903** [comment]
@jbod 
Email validator can not be changed from config_local.py. You need to provide email in  a valid format only.

**Comment by jbod** [comment]
Hi @yogeshmahajan-1903 

Thanks for your reply.

Does this mean that the `config_(local|system).py` tip to bypass .local email addresses mentionned in issues #6222, #6504 and #7668 does not work anymore?

**Comment by yogeshmahajan-1903** [comment]
I marking this as duplicate of #6222

**Comment by Joe136** [comment]
Hey, from the cryptic answer in https://github.com/pgadmin-org/pgadmin4/issues/6222#issuecomment-2368324322 I could properly bypass the check for __.local__ domains.

https://github.com/pgadmin-org/pgadmin4/blob/74c8b2d0a1f55fdcf3a90a061c1c34a4747a1d4d/web/pgadmin/utils/validation_utils.py#L33-L36

File: `docker-compose.yml`
```yaml
services:
    pgadmin:
        environment:
            PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS: '"local"'
```

For disabling multiple special domains, you can use (e.g. __.localhost__ and __.test__):

File: `docker-compose.yml`
```yaml
services:
    pgadmin:
        environment:
            PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS: '"localhost,test"'
```

The newer versions __additionally__ evaluates the email in the `entrypoint.sh` file. Therefore they use the function `validate_email()` in `/pgadmin4/pgadmin/utils/validation_utils.py`. To bypass the evaluation, replace the file with a dummy script. Disabling it in `config_local.py` is still required.

File: `./validation_utils.py` -> `/pgadmin4/pgadmin/utils/validation_utils.py`
```python
def validate_email(email, email_config=None):
    return True
```

File: `./config_local.py` -> `/pgadmin4/config_local.py`
```python
import email_validator
email_validator.SPECIAL_USE_DOMAIN_NAMES.remove("local")
# email_validator.SPECIAL_USE_DOMAIN_NAMES.remove("localhost")
# email_validator.SPECIAL_USE_DOMAIN_NAMES.remove("test")
```

File: `docker-compose.yml`
```yaml
services:
    pgadmin:
        volumes:
            - ./config_local.py:/pgadmin4/config_local.py:ro
            - ./validation_utils.py:/pgadmin4/pgadmin/utils/validation_utils.py:ro
```
