### ISSUE TITLE
pgAdmin export does not work on PostgreSQL 17

### ISSUE THREAD

**Issue by ryanhuangio** [pgadmin-org/pgadmin4#8047]
I am running pgAdmin in a docker container. I cannot export if the database server is PostgreSQL 17 because the pg_dump that comes with pgAdmin uses 16.4.

```
pg_dump: error: aborting because of server version mismatch
pg_dump: detail: server version: 17.0 (Debian 17.0-1.pgdg120+1); pg_dump version: 16.4
```

Here is my docker-compose.yml
```
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin
    restart: always
    ports:
      - '7878:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: 
      PGADMIN_DEFAULT_PASSWORD: 
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:
```
