### ISSUE TITLE
PGAdmin Hosted in AKS Redirect URI is incorrect

### ISSUE THREAD

**Issue by arunalakmal** [pgadmin-org/pgadmin4#8111]
**Describe the bug**

We have deployed the latest version of PGAdmin in AKS and exposed it using an NGINX ingress with an internal DNS and a Load Balancer. To make PGAdmin accessible from the on-premises network, we configured an Azure Application Gateway, setting the backend pool to point to the Ingress's internal URL.

The Application Gateway frontend has a unique URL, different from the internal Ingress URL, that allows access to PGAdmin from the on-premises network.

PGAdmin is also configured for OIDC authentication with Azure AD, with the OIDC redirect URI set to the Application Gateway frontend URL (on-prem URL, not the ingress URL). However, after users authenticate, the OIDC callback is directed to the internal Ingress URL instead, which is inaccessible externally.

Is there any way to configure PGAdmin to ensure it uses the correct URI (the Application Gateway frontend URL) for the callback after authentication? Currently, it seems to default to the Ingress URL rather than using the redirect URI defined in the Azure AD app registration.

**Expected behavior**

After the Azure AD Authentication call the correct call back url with the authentication.

**Comment by khushboovashi** [comment]
Hi @arunalakmal,

Once the user authenticated via any OAuth2 provider, the provider is responsible for the redirection to the pgAdmin. 
Can you please make sure, you have configured the Azure AD correctly ?

You can share all the NGINX, pgAdmin and Azure configurations here, so we can check it out.

**Comment by arunalakmal** [comment]
Hi @khushboovashi  Thank you for your reply! 

I found that , it is the azure app registration configurations responsibility and match the redirect URI. I can confirm it is the URL I access in the browser (https://CUSTOM_URL/oauth2/authorize is set in the redirect URI). But redirect comes from the url we use from the Ingress, it is not even added to the redirect URI in the Azure App Registration. 

Here is a little simplified diagram to understand more my networking flow: 
<img width="926" alt="Screenshot 2024-11-11 at 10 45 47" src="https://github.com/user-attachments/assets/73272a52-108f-40a5-b91b-113122c648ad">

Here is my OIDC Config in the PGAdmin: 
```
   OAUTH2_CONFIG = [
        {
            'OAUTH2_NAME': 'azure',
            'OAUTH2_DISPLAY_NAME': 'Azure',
            'OAUTH2_CLIENT_ID': os.environ['OAUTH2_CLIENT_ID'],
            'OAUTH2_CLIENT_SECRET': os.environ['OAUTH2_CLIENT_SECRET'],
            'OAUTH2_TOKEN_URL': 'https://login.microsoftonline.com/xxxxx-xxx-xx-xx-xxxxxxx/oauth2/v2.0/token',
            'OAUTH2_AUTHORIZATION_URL': 'https://login.microsoftonline.com/xxxxx-xxx-xx-xx-xxxxxxx/oauth2/v2.0/authorize',
            'OAUTH2_SERVER_METADATA_URL': 'https://login.microsoftonline.com/xxxxx-xxx-xx-xx-xxxxxxx/v2.0/.well-known/openid-configuration',
            'OAUTH2_API_BASE_URL': 'https://graph.microsoft.com/v1.0/',
            'OAUTH2_USERINFO_ENDPOINT': 'me',
            'OAUTH2_SCOPE': 'User.Read openid email profile',
            'OAUTH2_USERNAME_CLAIM': None,
            'OAUTH2_ICON': 'fa-microsoft',
            'OAUTH2_BUTTON_COLOR': '#0000ff',
            'OAUTH2_ADDITIONAL_CLAIMS': {
                'groups': ["xxxx-xxxx-xxxxx-xxxx-xxxxxxxx"],
                # 'wids': ["xxxx-xx-xxx-xxx-xxxxxxxx"],
              },
            'OAUTH2_SSL_CERT_VERIFICATION': True,
            'OAUTH2_LOGOUT_URL': None
        }
    ]
```

Also the values of these vars were set as below:

OAUTH2_AUTO_CREATE_USER = True
MASTER_PASSWORD_REQUIRED = False
AUTHENTICATION_SOURCES = ['oauth2','internal']
PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION = 'False'
PGADMIN_CONFIG_WTF_CSRF_ENABLED = 'False'
SERVER_MODE = 'True'
USE_X_FORWARDED_HOST = 'True'

I haven't used any overrides for PROXY_X_* variables and those are currently the default once. 

Do you have any recommendations or values updates to overcome with this? As per our network configuration, APP GW and Ingress Controller sitting behind the Internal LB can be act as two proxies. 

It would be really nice any recommendation you can provide for this.

**Comment by yogeshmahajan-1903** [comment]
@arunalakmal 
Can you please share your backend setting for App gateway? Also try setting PROXY_X_PROTO_COUNT and PROXY_X_PORT_COUNT = 2

**Comment by arunalakmal** [comment]
I did the `PROXY_X_PORT_COUNT = 2` and `PROXY_X_PROTO_COUNT = 2` and please find the below backend settings for the backend pool. 
<img width="819" alt="Screenshot 2024-11-11 at 13 04 31" src="https://github.com/user-attachments/assets/e596b2cc-ecee-45c9-a151-ff5f980d723d">

**Comment by yogeshmahajan-1903** [comment]
@arunalakmal 
Can you please check what is the value set for redirect_uri in headers like below?
<img width="1783" alt="Screenshot 2024-10-23 at 3 57 53 PM" src="https://github.com/user-attachments/assets/4adb62ab-12d6-47a3-9315-90c3927812d1">

**Comment by arunalakmal** [comment]
> @arunalakmal Can you please check what is the value set for redirect_uri in headers like below? <img alt="Screenshot 2024-10-23 at 3 57 53 PM" width="1783" src="https://private-user-images.githubusercontent.com/16016019/385240327-4adb62ab-12d6-47a3-9315-90c3927812d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MDcxMTgsIm5iZiI6MTczMTQwNjgxOCwicGF0aCI6Ii8xNjAxNjAxOS8zODUyNDAzMjctNGFkYjYyYWItMTJkNi00N2EzLTkzMTUtOTBjMzkyNzgxMmQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDEwMjAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkZDg5YWY2N2FhZTZkOWMzZGM4OTk0OGJmMmEyNjRlMmM4NGExYTc5Zjc4MGZjN2Y3ZmEyMmQ3NTZiOWVlYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jH3ilJiWqhIErYq2ouEkQ6bV8667xxy3fOnNfBgkfJs">

It's the `Ingress URL`, not the Front facing custom URI. That's where I confused and there is no option to define it and even it's not defined in the app registration call back URI. Can I override it?

**Comment by yogeshmahajan-1903** [comment]
@arunalakmal 
Screenshot attached is not visible. Can you please update? Can you please share deployment yaml?

**Comment by arunalakmal** [comment]
> @arunalakmal Can you please share deployment yaml?

Sure, here it is
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-tools-pgadmin
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: db-tools
      app.kubernetes.io/name: pgadmin
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: db-tools
        app.kubernetes.io/name: pgadmin
        helm-revision: "13"
    spec:
      containers:
      - env:
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            secretKeyRef:
              key: username
              name: db-tools-pgadmin
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: db-tools-pgadmin
        - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
          value: "False"
        - name: PGADMIN_CONFIG_WTF_CSRF_ENABLED
          value: "False"
        - name: SERVER_MODE
          value: "True"
        - name: USE_X_FORWARDED_HOST
          value: "True"
        - name: OAUTH2_CLIENT_ID
          value: xxxxxx
        - name: OAUTH2_CLIENT_SECRET
          value: xxxxxx
        image: dpage/pgadmin4:latest
        imagePullPolicy: IfNotPresent
        name: pgadmin
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /pgadmin4/config_local.py
          name: db-tools-custom-settings
          subPath: config_local.py
        - mountPath: /var/lib/pgadmin
          name: pgadmin
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: db-tools-pgadmin
      serviceAccountName: db-tools-pgadmin
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - configMap:
          defaultMode: 420
          name: db-tools-pgadmin-custom-settings
        name: db-tools-custom-settings
      - emptyDir: {}
        name: pgadmin
```

**Comment by yogeshmahajan-1903** [comment]
@arunalakmal 
Kindly share complete deployment config along with nginx deployment. I will try on our environment to reproduce the issue.

**Comment by arunalakmal** [comment]
@yogeshmahajan-1903 Here is the ingress resource created and whole setup is quite complex as I described earlier. I'm not sure how to share the whole thing. Our nginx Ingress deployed using a helm chart and the mostly with the default configurations. Configurations of the ingress controller is not quite significant and little old, if you can deploy the nginx ingress 4.4.2 (App version 1.5.1) with the below ingress then you have it. 

Azure setup is as I described earlier. 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: db-tools
    nginx.ingress.kubernetes.io/backend-protocol: HTTP"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
  labels:
    app.kubernetes.io/instance: db-tools
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pgadmin
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: pgadmin-0.1.0
  name: db-tools-pgadmin
spec:
  rules:
  - host: <INGRESS_URL>
    http:
      paths:
      - backend:
          service:
            name: db-tools-pgadmin
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
```

**Comment by yogeshmahajan-1903** [comment]
> @yogeshmahajan-1903 do you have any updates on this? were you be able to reproduce this?
> 
> At the meantime, we tried with some rewrite rules in Azure Application Gateway and were able to rewrite the response we got to the correct redirect_uri now we see a different issue. It's complaining about app registration redirect URI even thought both are added.
> 
> Now I see this error after the OIDC auth like this. Do you have any thoughts/config in PGAdmin perspective?
> 
> ```
> {
>     "success": 0,
>     "errormsg": "invalid_client: AADSTS500112: The reply address 'https://<backend_url>/oauth2/authorize' does not match the reply address 'https://<frontend_url>/oauth2/authorize' provided when requesting Authorization code. Trace ID: 03f2be04-53c6-482c-bf49-a08d43b21d00 Correlation ID: c480e120-4112-426c-af97-944c9e5b6937 Timestamp: 2024-11-25 08:54:17Z",
>     "info": "",
>     "result": null,
>     "data": null
> }
> ```
> 
> **Both are in the app registration redirection URI**

I washable to reproduce the issue but not exactly same as you as I did not have custom host name. However when I check logic for redirect url, it has host name which is picked from the request. However, backend setting created for Azure App Gateway has Hostname override as Yes, and pick hostname from backend as Yes. Hence it might be picking host name specified by ingress url. Can you try changing backend setting and check ? 

Meanwhile, can you please share the settings you have tried for rewriting response?

**Comment by arunalakmal** [comment]
> > @yogeshmahajan-1903 do you have any updates on this? were you be able to reproduce this?
> > At the meantime, we tried with some rewrite rules in Azure Application Gateway and were able to rewrite the response we got to the correct redirect_uri now we see a different issue. It's complaining about app registration redirect URI even thought both are added.
> > Now I see this error after the OIDC auth like this. Do you have any thoughts/config in PGAdmin perspective?
> > ```
> > {
> >     "success": 0,
> >     "errormsg": "invalid_client: AADSTS500112: The reply address 'https://<backend_url>/oauth2/authorize' does not match the reply address 'https://<frontend_url>/oauth2/authorize' provided when requesting Authorization code. Trace ID: 03f2be04-53c6-482c-bf49-a08d43b21d00 Correlation ID: c480e120-4112-426c-af97-944c9e5b6937 Timestamp: 2024-11-25 08:54:17Z",
> >     "info": "",
> >     "result": null,
> >     "data": null
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Both are in the app registration redirection URI**
> 
> I washable to reproduce the issue but not exactly same as you as I did not have custom host name. However when I check logic for redirect url, it has host name which is picked from the request. However, backend setting created for Azure App Gateway has Hostname override as Yes, and pick hostname from backend as Yes. Hence it might be picking host name specified by ingress url. Can you try changing backend setting and check ?
> 
> Meanwhile, can you please share the settings you have tried for rewriting response?

If I update the URL in the backend settings to frontend one manually it will not connect as it cannot be resolved, hence I set the picking from the backend. I did try that. Do you see any option to fix this like specifying the backend URI in the config instead of picking from the response? 

Here is the rewrite rule sets:

Rule 1: (It was a .com domain and Replace the Upper case letters with correct domain part)
```
IF:
  Type of variable to check: HTTP Header
  Header type: Response Header
  Header name: Common Header
  Common header: Location
  Case-sensitive: No
  Operator: Equal: (=) 
  Pattern to match: (.*)(redirect_uri=https%3A%2F%2F).*\.USE_BACKEND_DOMAIN_WITHOUT_COM\.com(.*)$
Then:
  Rewrite type: Response Header
  Action type: Set
  Header name: Common Header
  Common header: Location 
  Header value: {http_resp_Location_1}{http_resp_Location_2}{var_host}{http_resp_Location_3}
```

Rule 2: (It was a .com domain and Replace the Upper case letters with correct domain part)
```
IF:
  Type of variable to check: HTTP Header
  Header type: Response Header
  Header name: Common Header
  Common header: Location
  Case-sensitive: No
  Operator: Equal: (=) 
  Pattern to match: (https:\/\/).*\.USE_BACKEND_DOMAIN_WITHOUT_COM\.com(.*)$
Then:
  Rewrite type: Response Header
  Action type: Set
  Header name: Common Header
  Common header: Location 
  Header value: https://{var_host}{http_resp_Location_2}
```

After That I was getting this error, even thought both are in the redirect URI
```
{
    "success": 0,
    "errormsg": "invalid_client: AADSTS500112: The reply address 'https://<backend_url>/oauth2/authorize' does not match the reply address 'https://<frontend_url>/oauth2/authorize' provided when requesting Authorization code. Trace ID: 03f2be04-53c6-482c-bf49-a08d43b21d00 Correlation ID: c480e120-4112-426c-af97-944c9e5b6937 Timestamp: 2024-11-25 08:54:17Z",
    "info": "",
    "result": null,
    "data": null
}
```

Is this from an application security enhancement? Which we can disable and see?

**Comment by yogeshmahajan-1903** [comment]
@arunalakmal 
I guess what your are trying to achieve is not possible unless you same host name for external url and ingress url.
Please check this [link](https://www.patrickob.com/2022/04/06/azure-front-door-afd-app-gateway-app-service-unexpected-issues/) (Your problem is listed very first)

**Comment by arunalakmal** [comment]
> @arunalakmal I guess what your are trying to achieve is not possible unless you same host name for external url and ingress url. Please check this [link](https://www.patrickob.com/2022/04/06/azure-front-door-afd-app-gateway-app-service-unexpected-issues/) (Your problem is listed very first)

@yogeshmahajan-1903  Thanks for the reply. 

As I mentioned in the beginning of the issue, as a pattern this works. For example, I use ArgoCD to deploy the GitOps applications and it exposed with the same app gateway and two URLs one for backend and frontend. Works perfectly well years and **ONLY** PGAdmin has this issue.

**Comment by yogeshmahajan-1903** [comment]
@arunalakmal 
Kindly set PGADMIN_CONFIG_PROXY_X_HOST_COUNT to 1 and let rest parameter unchanged.
Here is my env variable list for pgadmin - 

```
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "admin@example.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "admin"
            - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
              value: "False"
            - name: PGADMIN_CONFIG_WTF_CSRF_ENABLED 
              value: "False"
            - name: PGADMIN_CONFIG_AUTHENTICATION_SOURCES
              value: "['internal','oauth2']"
            - name: PGADMIN_CONFIG_PROXY_X_HOST_COUNT
              value: "1"
            - name: PGADMIN_CONFIG_CONSOLE_LOG_LEVEL
              value : "10"
```

**Comment by arunalakmal** [comment]
@yogeshmahajan-1903 I tried and no luck, Please find my values below
```
PGADMIN_CONFIG_WTF_CSRF_ENABLED=False
SERVER_MODE=True
USE_X_FORWARDED_HOST=True
PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
PGADMIN_CONFIG_PROXY_X_HOST_COUNT=1
```

**Comment by yogeshmahajan-1903** [comment]
> @yogeshmahajan-1903 I tried and no luck, Please find my values below
> 
> ```
> PGADMIN_CONFIG_WTF_CSRF_ENABLED=False
> SERVER_MODE=True
> USE_X_FORWARDED_HOST=True
> PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
> PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
> PGADMIN_CONFIG_PROXY_X_HOST_COUNT=1
> ```

Have you removed rewrite settings? Also, please try removing rewrite settings. I was able to fix the issue with this setting. May if possible , we can connect over call.

**Comment by yogeshmahajan-1903** [comment]
@arunalakmal 
Can you please Nginx config for ingress controller?
```
helm get values <ingress_name> -n <name_space>
```

It should have ```use-forwarded-headers: true ``` . Mine looks as below - 
```
USER-SUPPLIED VALUES:
controller:
  config:
    use-forwarded-headers: true
  ingressClass: nginx
  service:
    externalTrafficPolicy: Local
```

Command to update config - 
```
helm upgrade ingress-nginx ingress-nginx/ingress-nginx -f values.yaml -n <name_space>
```
values.yaml - 
```
controller:
  ingressClass: nginx
  config:
    use-forwarded-headers: true
  service:
    externalTrafficPolicy: Local
```

Adding PGADMIN_CONFIG_PROXY_X_HOST_COUNT and above Nginx config should fix the issue.

**Comment by arunalakmal** [comment]
@yogeshmahajan-1903  Let me get back to you after trying this.

**Comment by arunalakmal** [comment]
@yogeshmahajan-1903 Unfortunately, it didn't make any difference in my case. Please find the below configurations of my Nginx ingress and the PGAdmin. 

```
USER-SUPPLIED VALUES:
controller:
  admissionWebhooks:
    patch:
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
  config:
    use-forwarded-headers: true
  extraArgs:
    default-ssl-certificate: ingress-nginx/ingress-default-cert
  image:
    digest: ""
    digestChroot: ""
    image: nginx
    registry: MYREGISTRY
    tag: 1.5.1
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      service.beta.kubernetes.io/azure-load-balancer-internal-subnet: cluster-nodes
    externalTrafficPolicy: Local
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
defaultBackend:
  serviceAccount:
    automountServiceAccountToken: true
serviceAccount:
  automountServiceAccountToken: true
```

These are the PGAdmin ENVs
```
PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
PGADMIN_CONFIG_WTF_CSRF_ENABLED=False
SERVER_MODE=True
USE_X_FORWARDED_HOST=True
PGADMIN_CONFIG_PROXY_X_HOST_COUNT=1
```

Also can you send me the `config_local.py`. Also If possible I'd like to connect over a call. 

It would be nice if you can share your PGAdmin deplpyment/helm chart as well.

**Comment by yogeshmahajan-1903** [comment]
I am not using any separate config_local file.
Here is my deployment file - 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:8.12
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "admin@example.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "admin"
            - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
              value: "False"
            - name: PGADMIN_CONFIG_WTF_CSRF_ENABLED 
              value: "False"
            - name: PGADMIN_CONFIG_AUTHENTICATION_SOURCES
              value: "['internal','oauth2']"
            - name: PGADMIN_CONFIG_PROXY_X_HOST_COUNT
              value: "1"
            - name: PGADMIN_CONFIG_CONSOLE_LOG_LEVEL
              value : "10"
            - name: PGADMIN_CONFIG_OAUTH2_CONFIG
              value: "[
        {
        'OAUTH2_USERNAME_CLAIM': 'login',
        'OAUTH2_NAME': 'github',
        'OAUTH2_DISPLAY_NAME': 'GitHub',
        'OAUTH2_CLIENT_ID': xxxxxxxxxxx,
        'OAUTH2_CLIENT_SECRET': xxxxxxxxxx,
        'OAUTH2_TOKEN_URL': 'https://github.com/login/oauth/access_token',
        'OAUTH2_AUTHORIZATION_URL': 'https://github.com/login/oauth/authorize',
        'OAUTH2_API_BASE_URL': 'https://api.github.com/',
        'OAUTH2_USERINFO_ENDPOINT': 'user',
        'OAUTH2_ICON': 'fa-github',
        'OAUTH2_BUTTON_COLOR': '#3253a8'
        }]"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
````

Ingress yaml - 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: pgadmin.internal.example.com  # Your internal DNS name here
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pgadmin
            port:
              number: 80
````
My working hours are 10 AM - 6 PM IST. Can you please invite to pgadmin-support@postgresql.org.
