### ISSUE TITLE
Unclear documentation wording: "not on subsequent launches using the same configuration database."

### ISSUE THREAD

**Issue by kasir-barati** [pgadmin-org/pgadmin4#8117]
Thanks for your commitment to this project and keeping its documentation up to date. I am currently trying to map a `servers.json` and `preferences.json` into pgadmin. So I was reading your doc and I kinda read it several times but did not manage to wrap my head around it. What does it mean by subsequent launches?

In docker personally just delete the containers in dev env and start them again. (`docker compose down -v`, and then `docker compose up -d`). So it kinda bugged me and since my mapping is not working right now (this is I guess a different matter, I'm mapping some files from my host into docker container but for some reason it does not map them at all :/) I was not able to verify what will happen if I:

- Remove the containers and start fresh.
- Just recreate the container by running `docker compose up -d` again after the first time.

Thus I am suggesting to rephrase or add a bit more details in these two places:

- https://github.com/pgadmin-org/pgadmin4/blob/b2782650055dd41c060cd016f29ecd5575cd1828/docs/en_US/container_deployment.rst?plain=1#L233-L237
- https://github.com/pgadmin-org/pgadmin4/blob/b2782650055dd41c060cd016f29ecd5575cd1828/docs/en_US/container_deployment.rst?plain=1#L241-L245

And "using the same configuration database" did not help me at all.

**Comment by kasir-barati** [comment]
BTW for those who are wondering what I did with my issue regarding pgadmin not mapping (binding) my `servers.json`, eventually I gave up on the idea of having a separate file and used the same `compose.yaml` file as here: https://stackoverflow.com/a/77519799/8784518

**Comment by yogeshmahajan-1903** [comment]
@kasir-barati 
1.'subsequent launches using the same configuration database.' pgadmin either uses sqlite database or  external database like postgres as pgadmin application database. 
Servers.json and preferences.json are loaded at first continuer creation and will not be updated on restart.

If you are using persistent volume  or external database, then servers.json and preferences.json will loaded only first time. If you restart container which uses **same** persistent volume or external database, then dat from  servers.json and preferences.json will not be again loaded because it is already present.

2. pgadmin image version used in docker-compose is 8.1. However, customisation using preferences.json is supported from 8.4 onwards.

3.Kindly share the log s for container where servers.json mapping did not work.
Here is typical example for docker compose - 
```
version: "3.8"
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./config/ServersToLoad.json:/pgadmin4/servers.json
      - ./config/PreferencesToSet.json:/pgadmin4/preferences.json
      
volumes:
  pgadmin-data:
    name: 'pgadmin-data'
```

My config directory had below files - 
1. PreferencesToSet.json
```
{
  "preferences":
    {
      "browser:display:show_system_objects":  true,
      "browser:display:show_user_defined_templates": true,
      "browser:display:confirm_on_refresh_close": false,
      "browser:prcoesses:prcoess_retain_days": 10
    }
}
```
2. ServersToLoad.json
```
{
  "Servers": {
      "1": {
          "Name": "PostgreSQL 16",
          "Group": "Servers",
          "Host": "localhost",
          "Port": 5432,
          "MaintenanceDB": "postgres",
          "Username": "postgres",
          "Comment": "Pg 16",
          "KerberosAuthentication": false,
          "ConnectionParameters": {
              "sslmode": "prefer",
              "connect_timeout": 10
            }
          }
      }
}
```
