### ISSUE TITLE
Query tools are not loaded with Firefox 134.0.1

### ISSUE THREAD

**Issue by cfrancois7** [pgadmin-org/pgadmin4#8372]
**Query tools are not loaded with Firefox**

The query tools are loaded with Edge and Chrome but not with firefox 134.0.1.
pgAdmin4 is launched with docker.

**To Reproduce**

- run the containers, docker-compose.yml
```
version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    volumes:
      - ./postgres_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_db:
    driver: local
```
- go to localhost:8080
- add your server (address is `postgres` and not localhost as it is in docker bridge network)
- try to load the query editors.

**Expected behavior**

The query editor opens when I click on `Query editor`.

**Error message**

No error is raised.
But I got two warnings from the firefox `console` (sorry it is french):
```
Propriété « -moz-border-radius » inconnue.  Déclaration abandonnée. [codemirror.css:244:22](chrome://devtools/content/shared/sourceeditor/codemirror/lib/codemirror.css)
Error while destroying front: objects-manager Error: Can't find the actor ID for objects-manager from root or target actor's form.
    getFront resource://devtools/shared/protocol/types.js:551
    getFront resource://devtools/client/fronts/targets/target-mixin.js:251
    releaseObjects resource://devtools/shared/commands/object/object-command.js:45
[target-mixin.js:458:19](resource://devtools/client/fronts/targets/target-mixin.js)
```

**Screenshots**
Left: Firefox, Right: Chrome (works with Edge too)

![Image](https://github.com/user-attachments/assets/f5bf7803-df55-44f3-aa4c-0b5428256fc6)

**Desktop:**
 - OS: Windows 10-WSL
 - Mode: Server
 - Browser: Firefox: 134.0.1 
 - Package type: Container
