### ISSUE TITLE
Unable to connect to server: [Errno 8] nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by zaratt** [pgadmin-org/pgadmin4#8645]
I'm trying to connect pgadmin to a container, but I get the message as shown in the image.
My docker compose settings below. What am I doing wrong?

**Error message**

Unable to connect to server: [Errno 8] nodename nor servname provided, or not known

**Screenshots**

![Image](https://github.com/user-attachments/assets/7b6379ea-b630-43c7-8c56-0fc656321c40)

**Desktop (please complete the following information):**
 - OS: Catalina
 - Version: 10.15
 - Mode: Desktop
 - Browser Chrome
 - Package type: Container

Docker Compose

`services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://user:password@postgres:5432/car_maintenance_db
    depends_on:
      - postgres

  frontend-web:
    build:
      context: ./frontend-web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend-web:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=car_maintenance_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:
[`](url)

**Comment by yogeshmahajan-1903** [comment]
@zaratt 
The docker compose looks good. Can you please check postgres contianer logs? Is it up and running & accepting the connections at 5432?

**Comment by khushboovashi** [comment]
@zaratt,  you have put postgres as your hostname.

**Comment by zaratt** [comment]
Hi @yogeshmahajan-1903 

I think yes. Look:

2025-04-08 19:17:59 2025-04-08 22:17:59.333 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-04-08 19:17:59 2025-04-08 22:17:59.333 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2025-04-08 19:17:59 2025-04-08 22:17:59.370 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-04-08 19:17:59 2025-04-08 22:17:59.377 UTC [29] LOG:  database system was shut down at 2025-04-07 23:04:40 UTC
2025-04-08 19:17:59 2025-04-08 22:17:59.422 UTC [1] LOG:  database system is ready to accept connections

Thanks

**Comment by yogeshmahajan-1903** [comment]
@zaratt 
I am not able to reproduce the issue. Can you please nslookup from pgadmin container with commmand below - 

```
 % docker exec -it <continaer id>  nslookup <postgres host name>

```

Expected output should be - 
```
Server:		127.0.0.11
Address:	127.0.0.11:53

Non-authoritative answer:

Non-authoritative answer:
Name:	postgres
Address: <some ip>
```

Which contianer enviroment are you using? I guessing issue could be with that.

Here is my docker-compose which works fine - 
```
services:
  postgres:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: edb
      POSTGRES_PASSWORD: adminedb
      POSTGRES_DB: car_maintenance_db
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: <user>
      PGADMIN_DEFAULT_PASSWORD: <pwd>
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
```
