### ISSUE TITLE
Ability to specify server password in config

### ISSUE THREAD

**Issue by mikesir87** [pgadmin-org/pgadmin4#8663]
**Describe the solution you'd like**

At Docker, we use pgadmin quite a bit in demos and in various dev environments to add a database visualizer and help with troubleshooting and debugging (thank you!). 

In these demo/dev environments, since the data is all local and non-sensitive, we configure the postgres password directly in the Compose file. While we mount in a `servers.json` and enable server mode, there's no way (that we've found) to specify the password for that server. This requires a user to put in a password immediately after opening pgadmin. 

We're thinking it would be a better user experience to have a way to supply this through some sort of configuration. That way, folks can simply open the app and jump right in.

And yes... we recognize this should _only_ be used for local development and not for production use cases.

**Describe alternatives you've considered**

Currently, we haven't found any other alternatives other than providing the password in the pgadmin interface when connecting to the database. In similar demos that use MySQL, we can use the `phpMyAdmin` image and specify environment variables to auto-connect.

**Additional context**

Sample Compose file:

```yaml
services:
  postgres:
    image: postgres:17.4
    ports:
      - "5432:5432"
    volumes:
      - ./dev/db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app

  pgadmin:
    image: dpage/pgadmin4:9.2.0
    ports:
      - "5050:80"
    volumes:
      - ./dev/pgadmin/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    depends_on:
      - postgres
```

And the `servers.json` looks like this:

```json
{
  "Servers": {
      "1": {
          "Name": "Local Postgres",
          "Group": "Servers",
          "Host": "postgres",
          "Port": 5432,
          "MaintenanceDB": "postgres",
          "Username": "postgres"
      }
  }
}
```

**Comment by yogeshmahajan-1903** [comment]
@mikesir87 
You can shared storage feature to pass the pgpas file - 
Here is docker-compose - 
```
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - "91:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
      PGADMIN_CONFIG_SHARED_STORAGE: "[{ 'name': 'Shared-pgpass', 'path': '/pgpassfolder', 'restricted_access': False }]"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./config/server3.json:/pgadmin4/servers.json
      - ./shared_dir/pgpass:/pgpassfolder
      
volumes:
  pgadmin-data:
    name: 'pgadmin-data'
```

servers.json - 
```
{
    "Servers": {
        "1": {
            "Name": "pg",
            "Group": "Servers",
            "Host": "<host>",
            "Port": 5439,
            "MaintenanceDB": "postgres",
            "Username": "postgres",
            "ConnectionParameters": {
                "sslmode": "prefer",
                "connect_timeout": 10,
                "passfile": "Shared-pgpass:/.pgpass"
            }
        }
    }
}
```

Here is directory - 
```
shared_dir % ls -la ../shared_dir/pgpass/
total 24
drwxrwxrwx  5   staff  160 Apr 23 16:22 .
drwx------  7  staff  224 Apr 23 16:25 ..
-rw-------  1  staff   27 Apr 23 15:47 .pgpass
 shared_dir %
```

**Comment by mikesir87** [comment]
Ah! I got it figured out. I wasn't thinking of using the passfile route before, so thanks for the pointer on that. I now have the following, which disables server mode and then enables a user to go directly to the database:

**compose.yaml**

```yaml
services:
  postgres:
    image: postgres:17.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalog

  pgadmin:
    image: dpage/pgadmin4:9.2.0
    ports:
      - "5050:80"
    volumes:
      - ./dev/pgadmin/servers.json:/pgadmin4/servers.json
      - ./dev/pgadmin/pgpass:/config/pgpass
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mycomp.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    depends_on:
      - postgres
```

**servers.json**
```json
{
  "Servers": {
      "1": {
          "Name": "Local Postgres",
          "Group": "Servers",
          "Host": "postgres",
          "Port": 5432,
          "MaintenanceDB": "postgres",
          "Username": "postgres",
          "PassFile": "/config/pgpass"
      }
  }
}
```

**pgpass**
```
*:*:*:postgres:postgres
```

**Comment by openscript** [comment]
@yogeshmahajan-1903 Unfortunately it still doesn't work:

```yml
networks:
  database:
    external: true
  proxy:
    external: true

volumes:
  postgres:
    driver: local

services:
  postgres:
    image: postgres:18.1
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - database
  pgadmin:
    image: dpage/pgadmin4:9.10.0
    environment:
      - "PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}"
      - "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}"
      - "PGADMIN_REPLACE_SERVERS_ON_STARTUP=True"
      - "PGADMIN_CONFIG_SHARED_STORAGE=[{ 'name': 'shared', 'path': '/shared', 'restricted_access': False }]"
      - "POSTGRES_HOST=postgres"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.example.com`)"
      - "traefik.http.routers.pgadmin.entrypoints=https"
      - "traefik.http.routers.pgadmin.tls=true"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
    depends_on:
      postgres:
        condition: service_healthy
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /shared/.pgpass
    networks:
      - database
      - proxy

configs:
  pgpass:
    content: |
      postgres:${POSTGRES_PORT}:*:${POSTGRES_USER}:${POSTGRES_PASSWORD}
  servers.json:
    content: |
      {
        "Servers": {
          "1": {
            "Name": "My Postgres",
            "Group": "Servers",
            "Host": "postgres",
            "Port": ${POSTGRES_PORT},
            "MaintenanceDB": "${POSTGRES_DB}",
            "Username": "${POSTGRES_USER}",
            "ConnectionParameters": {
                "sslmode": "prefer",
                "connect_timeout": 10,
                "passfile": "shared:/.pgpass"
            }
          }
        }
      }
```

A `.pgpass` file does exist at `/shared/.pgpass`:

```txt
5249d656b536:/pgadmin4$ ls -alh /shared/.pgpass 
-r--r--r--    1 root     root          58 Dec  3 07:57 /shared/.pgpass
```

```txt
5249d656b536:/pgadmin4$ cat /shared/.pgpass 
postgres:5432:*:robin:abcd*1234
```

No password is supplied:

<img width="1488" height="510" alt="Image" src="https://github.com/user-attachments/assets/7e1aebfe-a2e0-4dd6-931e-a4223710a1c7" />

Any idea what I'm doing wrong?

**Comment by GanymedeIndustries** [comment]
@openscript sorry a bit late but maybe try: `chown pgadmin:root /shared/.pgpass && chown 600 /shared/.pgpass`. I was in the same boat, albeit using it in desktop mode and referenced it directly instead of through shared storage, but kept on getting the same error until I changed the owner/permissions.

If the permissions were stopping you from reading the file then yes it would result in "no password supplied", but saying that no password was supplied BECAUSE the passfile could not be read would be more helpful

**Comment by openscript** [comment]
@GanymedeIndustries Thank you for writing! I eventually got it running (with 600 permissions):


```yml

networks:
  postgres:
    name: postgres
  proxy:
    external: true

volumes:
  postgres:
    driver: local

services:
  postgres:
    image: postgres:18.2
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:9.12.0
    restart: unless-stopped
    environment:
      - "PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}"
      - "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}"
      - "PGADMIN_REPLACE_SERVERS_ON_STARTUP=True"
      - "PGADMIN_CONFIG_X_CONTENT_TYPE_OPTIONS=''"
      - "PGADMIN_CONFIG_SHARED_STORAGE=[{ 'name': 'shared', 'path': '/shared', 'restricted_access': True }]"
      - "POSTGRES_HOST=postgres"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.example.com`)"
      - "traefik.http.routers.pgadmin.entrypoints=https"
      - "traefik.http.routers.pgadmin.tls=true"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:80/misc/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /shared/pgpass
        uid: "5050"
        gid: "5050"
        mode: 0600
    networks:
      - postgres
      - proxy

configs:
  pgpass:
    content: |
      postgres:${POSTGRES_PORT}:*:${POSTGRES_USER}:${POSTGRES_PASSWORD}
  servers.json:
    content: |
      {
        "Servers": {
          "1": {
            "Name": "example",
            "Group": "Servers",
            "Host": "postgres",
            "Port": ${POSTGRES_PORT},
            "MaintenanceDB": "${POSTGRES_DB}",
            "Username": "${POSTGRES_USER}",
            "PassFile": "shared:/pgpass"
          }
        }
      }
```
