### ISSUE TITLE
Store User account in External Database

### ISSUE THREAD

**Issue by wildhi** [pgadmin-org/pgadmin4#8738]
Hi,

we define in our Deployment an External Database (Postgres DB) for User settings.
https://www.pgadmin.org/docs/pgadmin4/9.1/external_database.html

Example
```yaml
  CONFIG_DATABASE_URI =
    'postgresql://DBUSER:*********@DNS:PORT/DBNAME'
```
This is define in `config-py` like the Docs
https://www.pgadmin.org/docs/pgadmin4/9.1/config_py.html#config-py

But we need to store the Local Users into this External postgres Database. But i can´t define the External Database, the setting with docs is only referenze the SQLite DB which is stored in Pod.

Is there a setting to store Users into External Database ?

**Comment by pravesh-sharma** [comment]
Hi @wildhi,

Can you please share deployment yml file. You need to add prefix `PGADMIN_CONFIG` to the parameters that you want to override from `config.py`

**Comment by wildhi** [comment]
Hi @pravesh-sharma i´m not sure what do you need. We deploy a Helm Chart in our K8S and define the `config-py` with a ConfigMap where is declare the `CONFIG_DATABASE_URI`.

With Parameter `PGADMIN_CONFIG` what do you mean should i define ?

**Comment by pravesh-sharma** [comment]
Hi @wildhi,

Are you able to run pgAdmin? Do you get any error or warning? Please share the log files.

**Comment by wildhi** [comment]
Hi @pravesh-sharma 
this is my helm deployment file
```yaml
# helm upgrade --install -n pgadmin pgadmin-test -f values_test.yaml runix/pgadmin4
# k8s0-q

replicaCount: 1
image:
  registry: artifacts.endress.com/docker-mirror
  repository: dpage/pgadmin4
  tag: "8.14"
  pullPolicy: IfNotPresent

annotations: {}

service:
  type: ClusterIP
  port: 80
  targetPort: http
  portName: http
  annotations: {}
serviceAccount:  
  create: false
  annotations: {}
  name: ""
strategy:
  type: Recreate
serverDefinitions:
  enabled: false
  servers: |-
  #  "1": {
  #    "Name": "Minimally Defined Server",
  #    "Group": "Servers",
  #    "Port": 5432,
  #    "Username": "postgres",
  #    "Host": "localhost",
  #    "SSLMode": "prefer",
  #    "MaintenanceDB": "postgres"
  #  }
networkPolicy:
  enabled: true
ingress:
  enabled: enable
  annotations: {}
  hosts:
    - host: DNS
      paths:
        - path: /
          pathType: Prefix
  tls: 
   - secretName: naming
     hosts:
       - DNS

extraConfigmapMounts:
  - name: servers
    mountPath: /pgadmin4/servers.json
    subPath: servers.json
    configMap: servers
    readOnly: true
  - name: pgadminconfig
    mountPath: /pgadmin4/config_local.py
    subPath: config_local.py
    configMap: pgadminconfig
    readOnly: true
  - name: 	pgadminconfigdistro
    mountPath: /pgadmin4/	config_distro.py
    subPath: 	config_distro.py
    configMap: 	pgadminconfigdistro
    readOnly: true

existingSecret: "testpgadmin"

env:
  email: test@test.com
  enhanced_cookie_protection: "False"
  variables: []

persistentVolume:
  enabled: true
  annotations: {}
  accessModes:
    - ReadWriteOnce
  size: 10Gi
securityContext:
  runAsUser: 5050
  runAsGroup: 5050
  fsGroup: 5050

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 60
  timeoutSeconds: 15
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 60
  timeoutSeconds: 15
  successThreshold: 1
  failureThreshold: 3

VolumePermissions:
  enabled: false
extraInitContainers: |
#   - name: add-folder-for-pgpass
#     image: "dpage/pgadmin4:latest"
#     command: ["/bin/mkdir", "-p", "/var/lib/pgadmin/storage/pgadmin"]
#     volumeMounts:
#       - name: pgadmin-data
#         mountPath: /var/lib/pgadmin
#     securityContext:
#       runAsUser: 5050
containerPorts:
  http: 80

resources:
  limits:
    cpu: 400m
    memory: 512Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
podAnnotations: {}
podLabels: {}
init:
  resources: {}
test:
  image:
    registry: artifacts.endress.com/docker-mirror
    repository: busybox
    tag: latest
  resources: {}
  securityContext:
    runAsUser: 5051
    runAsGroup: 5051
    fsGroup: 5051
```

with this we deploy a Pod in our Kubernetes. I want to define a external Postgres Database for have a Persistency for Users. 
How can i do this ?

thx

**Comment by yogeshmahajan-1903** [comment]
@wildhi 
Can you please share your 'templates/deployment.yaml'. It should have below env set in the container specs - 
E.g - 

```
env:
        - name: PGADMIN_DEFAULT_EMAIL
           value: "{{ .Values.pgadmin.email }}"
        - name: PGADMIN_CONFIG _CONFIG_DATABASE_URI
           value: "{{ .Values.pgadmin.configDatabaseURI }}"
....
```

values.yaml
```
pgadmin:
  image: dpage/pgadmin4
  tag: 8.5

 .
 .

 configDatabaseURI: "postgresql://pgadmin_user:pgadmin_pass@db.example.com:5432/pgadmin"
```
