### ISSUE TITLE
Failed to decrypt the saved password

### ISSUE THREAD

**Issue by amirhossein-deriv** [pgadmin-org/pgadmin4#8776]
**Describe the bug**

We upgraded our pgAdmin to V9.3, now there are two kind of issues:
1. the saved password for one user gets error: 
```
Failed to decrypt the saved password. Error: 'utf-8' codec can't decode byte 0xaf in position 1: invalid start byte

```
and

```
Failed to decrypt the saved password. Error: 'utf-8' codec can't decode byte Oxd5 in position 0: invalid continuation byte
```
to solve this issue regarding our online research we find these links helpful and based on them we cleared the passwords for all connections and setup them.

[https://www.pgadmin.org/docs/pgadmin4/9.3/clear_saved_passwords.html](https://www.pgadmin.org/docs/pgadmin4/9.3/clear_saved_passwords.html
)
[https://stackoverflow.com/questions/56526882/pgadmin-error-failed-to-decrypt-the-saved-password](https://stackoverflow.com/questions/56526882/pgadmin-error-failed-to-decrypt-the-saved-password)

2. We have the second  issue that raised after the other one:
```
connection failed: connection to server at "xx.xx.xx.xx", port 5432 failed: fe_sendauth: no password supplied
```

**To Reproduce**

1. upgrade version 8.12 to 9.3
2. See the error

**Expected behavior**

Regarding the issue posted from older versions, it should be solved and don't raise again. 

**Error message**

Failed to decrypt the saved password. Error: 'utf-8' codec can't decode byte 0xaf in position 1: invalid start byte

Failed to decrypt the saved password. Error: 'utf-8' codec can't decode byte Oxd5 in position 0: invalid continuation byte

**Screenshots**

<img width="608" alt="Image" src="https://github.com/user-attachments/assets/80df025a-a1ff-4bbd-b04b-0240d5f74c8c" />

![Image](https://github.com/user-attachments/assets/7aded7a9-6b01-4369-a3fb-b8c89333d60a)

**Docker:**
 - image: dpage/pgadmin4:9.3
 - Version: [e.g. 6.15]
 - Mode: [e.g Desktop or Server]
 - Browser: chrome
 - Package type: Container

**unsolved lssue:**
[https://github.com/pgadmin-org/pgadmin4/issues/5487](https://github.com/pgadmin-org/pgadmin4/issues/5487)

**Comment by yogeshmahajan-1903** [comment]
@amirhossein-deriv 
I am not able to reproduce the issue with upgrade. Are you using OAtuh2 authentication source? Can you please share your pgadmin container deployment file?

**Comment by akshay-joshi** [comment]
No response from the author, hence closing it.

**Comment by omar-binary** [comment]
Hi @akshay-joshi / @yogeshmahajan-1903 ,
Thank you for looking into this, we are not using OAtuh2 authentication.

sharing below our pgadmin info
```
Version 9.5
Application Mode Server
Commit a5714903acb250481a987f3e352680b7a66403b5 2025-06-27
Python Version 3.12.11
Browser Chrome 139.0.0.0
Operating System Alpine Linux v3.22, Linux-5.10.0-35-cloud-amd64-x86_64-with
pgAdmin Database File /var/lib/pgadmin/pgadmin4.db
```

And this is our PgAdmin Docker compose file
```
version: '3.7'
services:
  pgadmin:
    image: dpage/pgadmin4:9.5
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 4G
    ports:
      - 8001:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=<REDACTED>
      - PGADMIN_DEFAULT_PASSWORD=<REDACTED>
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
      - PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT=False
    volumes:
      - type: bind
        source: /data/pgadmin
        target: /var/lib/pgadmin
      - type: bind
        source: /data/pgadmin/servers.json
        target: /pgadmin/servers.json
```

please do let us know if anything else we can provide to help replicating this
